### ISSUE TITLE
Add support for ServiceConnectorConfig on generic services

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-connectors#102]
When using ServiceConnectionFactory there's no way to pass a custom ServiceConnectorConfig on the generic implementation of service methods: https://github.com/spring-cloud/spring-cloud-connectors/blob/3ec88aba9ed85f2b09d2cafb620ad1d4a28aaa9d/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/config/java/AbstractCloudConfig.java#L419

Adding this would allow new connectors to support custom configuration.

**Comment by scottfrederick** [comment]
Fixed in #103
