### ISSUE TITLE
Should be able to set the RedisConnection timout with the ServiceConnectorConfig

### ISSUE THREAD

**Issue by cgfrost** [spring-cloud/spring-cloud-connectors#108]
Sometimes it takes too long to connect to a Redis instance and the default time out gets hit. It should be possible to specify a different time out in the ServiceConnectorConfig object.

https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/service/keyval/RedisConnectionFactoryCreator.java

**Comment by scottfrederick** [comment]
@cgfrost We've been getting a few requests lately to add more ability to customize the connections created by SCC. There is a [`RedisConnectionFactoryConfigurer`](https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/service/keyval/RedisConnectionFactoryConfigurer.java) that provides some customization ability, and we can add more fields that that `Configurer` that would be honored when the `ConnectionFactory` is created.

**Comment by scottfrederick** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-connectors/commit/30c40dd0d8ed6b884cc516a98ce068f8bc1b0d56

This change allows a map of connection properties to be provided to customize the created `RedisConnectionFactory` bean. 

With XML configuration, you can now do something like this: 
```
<cloud:redis-connection-factory id="redis" service-name="my-redis">
    <cloud:connection-properties>
        <entry key="timeout" value="10"/>
    </cloud:connection-properties>
</cloud:redis-connection-factory>
```

With Java config, you can now do something like this: 
```
@Configuration
class RedisConfig extends AbstractCloudConfig {
	@Bean
	public RedisConnectionFactory redisConnectionFactory() {
		Map<String, Object> properties = new HashMap<String, Object>();
		properties.put("timeout", 10);
		RedisConnectionFactoryConfig serviceConfig = new RedisConnectionFactoryConfig(properties);
		return connectionFactory().redisConnectionFactory("my-redis", serviceConfig);
	}
}
```
