### ISSUE TITLE
Allow setting connection parameters for JDBC connections

### ISSUE THREAD

**Issue by jbcpollak** [spring-cloud/spring-cloud-connectors#117]
I am using Spring Cloud with Pivotal Web Services and a ClearDB provided MySQL database. It seems the connection is not using utf8, and I cannot figure out how to set it. 

Traditionally with Spring Boot you would do something like this:

    spring.datasource.url=jdbc:mysql://localhost:13306/app_dev?autoReconnect=true&amp;characterEncoding=utf8

How can you do this with cloud connectors?

**Comment by ramnivas** [comment]
Take a look at (towards the end of) https://spring.io/blog/2014/06/03/introducing-spring-cloud as well as [a test case that illustrates the solution](https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/test/java/org/springframework/cloud/config/java/DataSourceJavaConfigTest.java#L60).
