### ISSUE TITLE
TomcatDbcpPooledDataSourceCreator does not work with Tomcat 8

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud/spring-cloud-connectors#125]
`TomcatDbcpPooledDataSourceCreator` looks for `org.apache.tomcat.dbcp.dbcp.BasicDataSource` on the classpath. This doesn't work with Tomcat 8 as this class does not exist. The Tomcat 8 equivalent is 
`org.apache.tomcat.dbcp.dbcp2.BasicDataSource`

I found the problem when building the Spring IO Platform. `PooledDataSourceCreatorsTest.pooledDataSourceCreationTomcatDbcp` fails when tested against Tomcat 8 is the creator returns `null`.

Would it be possible to enhance `TomcatDbcpPooledDataSourceCreator` so that it supports both Tomcat 7 and Tomcat 8 and the tests pass when run against either version of Tomcat?

**Comment by scottfrederick** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-connectors/commit/e3eae31995d56c7b5d8cc7fcbc2513cd911a1725
