### ISSUE TITLE
No RabbitServiceInfo

### ISSUE THREAD

**Issue by nadkau-pivotal** [spring-cloud/spring-cloud-connectors#135]
I'm unable to find RabbitServiceInfo in this repo.
I suspect RabbitServiceInfo should be here.

**Comment by scottfrederick** [comment]
The class you are probably looking for is [`AmqpServiceInfo`](https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-core/src/main/java/org/springframework/cloud/service/common/AmqpServiceInfo.java). This is designed to work with RabbitMQ and other implementations of AMQP like [Qpid](https://github.com/spring-cloud/spring-cloud-connectors/issues/110), hence the name.
