### ISSUE TITLE
Change order of connection pooling DataSource detection

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud/spring-cloud-connectors#139]
The Spring Connectors will detect the presence of connection pooling `DataSource` implementations on the classpath, and use the first one it finds in this order: 

* Apache Commons DBCP and DBCP 2 pooling
* Tomcat DBCP
* Tomcat JDBC Connection Pool
* HikariCP

It has been [suggested](https://github.com/spring-cloud/spring-cloud-connectors/issues/131) that it would be better to put the higher-performing implementations (Tomcat JDBC and HikaraCP) ahead of the lower-performing DBCP options. Most apps would only have one implementation on the classpath, and changing the order would have no affect on these apps. For apps that do have more than one impl on the classpath changing the order might cause a surprise.

**Comment by scottfrederick** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-connectors/commit/05930a4e735236a5eac82d9d731e019f476bf19c

The order of detection now matches the order used by [Spring Boot](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-connect-to-production-database): 

* Tomcat JDBC Connection Pool
* HikariCP
* Tomcat DBCP
* Apache Commons DBCP and DBCP 2 pooling

**Comment by C-Otto** [comment]
@scottfrederick Could you also update http://cloud.spring.io/spring-cloud-connectors/spring-cloud-spring-service-connector.html#_reordering_implementation_priority accordingly?

**Comment by C-Otto** [comment]
Sorry, I meant http://cloud.spring.io/spring-cloud-connectors/spring-cloud-spring-service-connector.html#_detection_and_prioritization_of_code_datasource_code_implementations_2

**Comment by scottfrederick** [comment]
@fifthposition Can you update this in the docs when you get a chance?
