### ISSUE TITLE
PostgresqlServiceInfoCreator cannot create info - does not recognize postgresql scheme

### ISSUE THREAD

**Issue by wujek-srujek** [spring-cloud/spring-cloud-connectors#140]
Hi. I have an issue which prevents the PostgresqlServiceInfoCreator from creating a PostgresqlServiceInfo. The Cloud Foundry VCAP_SERVICES part for Postgres looks like this:
"postgres": [
   {
    "credentials": {
     "host": "host",
     "jdbcUrl": "jdbc:postgresql://host:5432/db",
     "name": "db",
     "password": "pass",
     "port": 5432,
     "uri": "postgresql://host:5432/db",
     "username": "user"
    },
    "label": "postgres",
    "name": "postgres_db",
    "plan": "10gb",
    "tags": []
   }
  ]

As you can see, the scheme is 'postgresql', and the creator keeps looking for 'postgres'. All the other ways of checking for the service type fail for these variables.

How can I make this work? Would it somehow be possible to extend the class to also check the 'postgresql' scheme?

**Comment by wujek-srujek** [comment]
I guess this has been addressed with commits https://github.com/spring-cloud/spring-cloud-connectors/commit/6f1b17d12d03bbfa89e4e4daa4b9460c416e846f and https://github.com/spring-cloud/spring-cloud-connectors/commit/86780fbc60ab5a91fc64a951dcf46b070d7aa753?
When will a release be made?

**Comment by scottfrederick** [comment]
Yes, I noticed this problem with postgres schemes when making the changes you noted above. A 1.2.1 release will be published very soon.
