### ISSUE TITLE
Support SendGrid Explicitly

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-connectors#145]
SendGrid recommends using the Java API  - https://github.com/sendgrid/sendgrid-java 
Furthermore, this might provide a better user-experience than having to use the Java/Spring abstractions.

**Comment by scottfrederick** [comment]
@ghillert I think it is better for Connectors to deal with abstractions rather than vendor-specific libraries. SendGrid is the only mail service provider I've seen in the CF marketplace, but the SMTP support in Connectors could support others.
