### ISSUE TITLE
Add support for heroku-redis in spring-cloud-heroku-connector

### ISSUE THREAD

**Issue by beccagaspard** [spring-cloud/spring-cloud-connectors#146]
heroku-redis plugin is using environment variable REDIS_URL

[heroku redis plugin](https://elements.heroku.com/addons/heroku-redis)
[heroku redis documentation](https://devcenter.heroku.com/articles/heroku-redis#create-a-new-instance)

**Comment by scottfrederick** [comment]
Closed via #147.
