### ISSUE TITLE
What are the purpose of the .adoc files, and should the .md files be generated from .adocs?

### ISSUE THREAD

**Issue by jadekler** [spring-cloud/spring-cloud-connectors#149]

**Comment by jadekler** [comment]
Happy to make a PR for the latter, just want to make sure I'm not stepping on feet beforehand.

**Comment by scottfrederick** [comment]
The .adoc Asciidoctor files in the `/docs/` directory are used to generate the documentation published to http://cloud.spring.io/spring-cloud-connectors/spring-cloud-connectors.html. This is the way forward for Spring Cloud documentation (including Connectors). The .md files in the repo will be removed soon, as the published docs replace this content.

**Comment by jadekler** [comment]
Aha, thanks @scottfrederick
