### ISSUE TITLE
Cloud Connector tries to configure DB2Service erroneously. We don't use DB2 at all.

### ISSUE THREAD

**Issue by raphsoft** [spring-cloud/spring-cloud-connectors#156]
I have an Spring Boot Application that I want to Bind to a SSO Service Instance provided by Cloud Foundry, so I added this dependencies to my project: 

```
compile 'org.springframework.cloud:spring-cloud-starter-oauth2'
compile 'org.springframework.cloud:spring-cloud-cloudfoundry-connector:1.2.0.RELEASE'
compile 'io.pivotal.spring.cloud:spring-cloud-sso-connector:1.1.0.RC1'
```
Then added the @EnableOAuth2Sso annotation to my main configuration class.
So the issue is that application fails because somehow the connector is trying to instantiate a  DB2ServiceInfoCreator. Actually I provide DataSource configurations using spring.datasource.* properties as the CF Environment in my Organization does not offer any Oracle Service thus we access to an external Oracle Database Server.

```
 [APP/0]      ERR Caused by: java.util.ServiceConfigurationError: org.springframework.cloud.cloudfoundry.CloudFoundryServiceInfoCreator: 
Provider org.springframework.cloud.cloudfoundry.DB2ServiceInfoCreator could not be instantiated
 [APP/0]      ERR    at java.util.ServiceLoader.fail(ServiceLoader.java:232)
 [APP/0]      ERR    at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
 [APP/0]      ERR    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
 [APP/0]      ERR    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
 [APP/0]      ERR    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
 [APP/0]      ERR    at org.springframework.cloud.AbstractCloudConnector.scanServiceInfoCreators(AbstractCloudConnector.java:53)
 [APP/0]      ERR    at org.springframework.cloud.AbstractCloudConnector.<init>(AbstractCloudConnector.java:33)
 [APP/0]      ERR    at org.springframework.cloud.cloudfoundry.CloudFoundryConnector.<init>(CloudFoundryConnector.java:32)
 [APP/0]      ERR    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 [APP/0]      ERR    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 [APP/0]      ERR    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 [APP/0]      ERR    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
 [APP/0]      ERR    at java.lang.Class.newInstance(Class.java:442)
 [APP/0]      ERR    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
 [APP/0]      ERR    ... 29 more
 [APP/0]      ERR Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/service/common/DB2ServiceInfo

```

**Comment by raphsoft** [comment]
Hello Dave @dsyer, do you think this can be a bug? Maybe you know someone that can provide guidance with connectors.

**Comment by dsyer** [comment]
@scottfrederick is the lead on this project. If it's a bug it doesn't look like you would be the only one to experience it. What version of connectors are you using?

**Comment by raphsoft** [comment]
I'm using spring-cloud-cloudfoundry-connector version 1.2.0.RELEASE and  spring-cloud-sso-connector version 1.1.0.RC1

What I have is an @Autowired javax.sql.Datasource object inside a @Configuration class and as I understand the connector tries to discover an SQL Service which we don't have because we use external databases. So, instead of creating the Datasource object using the spring.datasource.* properties it throws that error.

I was also looking for documentation that allows me to instruct the connector to create and bind only the services I want. I this case, I only need the connector to enable SSO Integration, so all other configuration keeps working with our spring-cloud-config-server.

**Comment by scottfrederick** [comment]
The `java.lang.NoClassDefFoundError: org/springframework/cloud/service/common/DB2ServiceInfo` error would indicate that you are getting mismatched versions of Spring Cloud Connectors dependencies. The library is not actually trying to create a DB2 connection, just trying to resolve classes at load time. 

There are three dependencies you will likely need in this configuration - `spring-cloud-cloudfoundry-connector`, `spring-cloud-spring-service-connector`, and `spring-cloud-core`. You are explicitly depending on the first one, and are likely getting the other two transitively with versions other than the `1.2.0.RELEASE` that you specify for the cloudfoundry-connector. 

Spring Boot will pull in (likely older) versions of the Connectors dependencies, and `spring-cloud-sso-connector` depends on the core libs also. 

You can either explicitly declare all three of these dependences with matching versions, or you might be able to [configure the version that Spring Boot depends on](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-build.html#howto-customize-dependency-versions) to get them all to match.

**Comment by raphsoft** [comment]
Thank you so much for clarification. In effect, it's a dependency version issue. However, I'm trying to figure out which versions will be the correct ones if I have the following configuration:

```
dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-starter-parent:Brixton.M4'
    }
}
```

As I understand from the documentation, the version of the Cloud Foundry Connector for the Brixton.M4 release train should be 1.0.0.RELEASE, but the version I need to use is 1.2.0.RELEASE:

![image](https://cloud.githubusercontent.com/assets/8571102/12543561/8d45bd30-c2fe-11e5-9c73-e7036c459757.png)

So I guess my question now is... which version should I use for dependencyManagement configuration as with the previous configuration plus connector and cloud-core 1.2.0.RELEASE I start to have problems with the config-client instead (as it appears to be trying to use version 1.1.0)

**Comment by scottfrederick** [comment]
Connectors is not part of the Spring Cloud release train, and no Spring Cloud projects have a dependency on Connectors. Connectors existed before the rest of Spring Cloud, and while it is under the same umbrella its versions are tracked separately. 

Spring Boot does have a dependency on Connectors, which is likely where the `1.0.0.RELEASE` versions of `core` and `spring-service-connector` are coming from. You should just pull in `1.2.0.RELEASE` (or `1.2.1.RELEASE`).

**Comment by raphsoft** [comment]
Thank you for your reply. You were totally right, I managed to get everything working with your suggestions. I think you can close this issue now.
