### ISSUE TITLE
Incompatible changes of constructor signature with 1.2.1

### ISSUE THREAD

**Issue by steinermatt** [spring-cloud/spring-cloud-connectors#159]
Hi there,

just wanted to chime in to raise concerns about such drastic changes as introduced with 1.2.1. 

The new constructor signature of [RelationalServiceInfo](https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-core/src/main/java/org/springframework/cloud/service/common/RelationalServiceInfo.java#L16) now requires four parameter instead of three (as prior to 1.2.1), causing our own implementation to throw class loading issues!

![spring-cloud](https://cloud.githubusercontent.com/assets/2083859/13008857/5c1b398e-d199-11e5-8d52-b8ad9673402e.png)

Any chance you can provide a fall-back default requiring only the original parameter?

Best regards,
matthias

**Comment by scottfrederick** [comment]
Thanks @steinermatt. You're right, a bump in the "patch" version (e.g. from 1.2.0 to 1.2.1) shouldn't introduce a backward-incompatible API change. I'll look into adding a three-parameter form of that constructor back into `RelationalServiceInfo`.

**Comment by scottfrederick** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-connectors/commit/7521d4be4d66721d3ed280d6bad912be5a055d86.

**Comment by scottfrederick** [comment]
@steinermatt Please test this fix with 1.2.2.BUILD-SNAPSHOT from repo.spring.io/libs-snapshot at your convenience. If this works I should be able to get 1.2.2.RELEASE out pretty quickly.

**Comment by C-Otto** [comment]
@scottfrederick I just tested the snapshot with @steinermatt's library: everything works as expected. I'd love to see a 1.2.2 RELEASE.

**Comment by steinermatt** [comment]
@scottfrederick I can confirm as well! Thanks for the quick fix! 

If you could provide  1.2.2.RELEASE that would be fabulous!

**Comment by C-Otto** [comment]
@scottfrederick I just found another user getting hit by this bug. Could you please release the fix soon?

**Comment by scottfrederick** [comment]
@C-Otto @steinermatt 1.2.2.RELEASE has been published to repo.spring.io/libs-release. It should get propagated to Maven Central soon. Apologies for the delay in getting the release published.
