### ISSUE TITLE
Extension project to add s3 connectors 

### ISSUE THREAD

**Issue by ArthurHlt** [spring-cloud/spring-cloud-connectors#162]
I've made extension project to add s3 connectors for heroku, cloudfoundry and local config. It use [jclouds](https://jclouds.apache.org/) as blobstore context.

@scottfrederick if you still want to add it to the  "Community Extensions" section the project his located here: https://github.com/Orange-OpenSource/spring-cloud-s3-connectors

This issue is related to the PR: https://github.com/spring-cloud/spring-cloud-connectors/pull/160

**Comment by scottfrederick** [comment]
@ArthurHlt this looks great. We will get the link added to the community extensions list.

**Comment by ArthurHlt** [comment]
that's would be great, thank you

**Comment by scottfrederick** [comment]
S3 extension has been added: http://cloud.spring.io/spring-cloud-connectors/

**Comment by ArthurHlt** [comment]
Thank you, you make a young software engineer happy (me)
