### ISSUE TITLE
Misleading Instructions in Cloud Foundry Documentation

### ISSUE THREAD

**Issue by juanjose49** [spring-cloud/spring-cloud-connectors#168]
The instructions I'm referring to can be found in the following URL: [HERE](http://cloud.spring.io/spring-cloud-connectors/spring-cloud-cloud-foundry-connector.html)

I was trying to follow the instructions to set up an Oracle database using the Cloud Foundry Connector and found the instructions were misleading by including all the following options as keys that could be included in the VCAP_SERVICES environment variable:
> uri or uris using the scheme oracle
> jdbcUrl field in credentials using the scheme oracle
> oracleUri, oracleuri, oracleUrl, or oracleurl fields in credentials

After debugging, I found that the only key that the connector responds to is the "jdbcUrl" key. Can you please revise the documentation to reflect that you must use the "jdbcUrl" key and that none of the other options work?

Additionally, will you please consider adding sample VCAP_SERVICES JSON documents as examples for each type of datasource?

Thank you!
Juan

**Comment by scottfrederick** [comment]
@juanjose49 It is surprising to hear that you couldn't get anything except the `jdbcUrl` key to work. I haven't seen this reported anywhere else, and we have several unit tests to verify that the different detection options work: 

* https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-cloudfoundry-connector/src/test/java/org/springframework/cloud/cloudfoundry/CloudFoundryConnectorOracleServiceTest.java
* https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/test/java/org/springframework/cloud/service/relational/OracleDataSourceFactoryTest.java

I assume you are using user-provided service instances when connecting to the Oracle database. Can you provide some examples of the `cf create-user-provided-service` command you used to create the service instance and the resulting `VCAP_SERVICES` seen by the application to help figure out what you are seeing?

**Comment by scottfrederick** [comment]
@juanjose49 As requested above, you can provide more information to help reproduce this problem?

**Comment by scottfrederick** [comment]
@juanjose49 Some docs clarifications were made here: 5d06861ef19dabc35cb4d7f1ae54f66f4f56c91d. Please re-open this issue and add more details if you are still having problems.
