### ISSUE TITLE
o.s.c.s.r.DataSourceConfig.ConnectionConfig not taking into account pg's currentSchema JDBC connection parameter

### ISSUE THREAD

**Issue by balteo** [spring-cloud/spring-cloud-connectors#174]
I noticed that SCC's `DataSourceConfig.ConnectionConfig` does not take into account Postgresql's `currentSchema` jdbc connection parameter (and I guess other pg connection parameters).

Is this a bug?

Here is my configuration:

```
@Configuration
@Profile({Profiles.CLOUD, Profiles.DEV})
public class DataSourceConfiguration extends AbstractCloudConfig {

    @Bean
    @Qualifier("application_database")
    @Primary
    public DataSource applicationDatasource() {
        ConnectionConfig connConfig = new ConnectionConfig("currentSchema=application");//This is not taken into account
        Map<String, Object> connProperties = new HashMap<>();
        connProperties.put("poolName", "myPool");
        DataSourceConfig dbConfig = new DataSourceConfig(null, connConfig, null, connProperties);
        return connectionFactory().dataSource("application_database", dbConfig);
    }
}
```

and from `spring-cloud.properties`: 

`spring.cloud.application_database=postgres://postgres:postgres@localhost:5432/bignibou`

I could get it to work as follows: `spring.cloud.application_database=postgres://postgres:postgres@localhost:5432/bignibou?currentSchema=application` but I need to avoid specifying the current schema within `spring-cloud.properties` because this is specific to spring cloud connector local config and will not work in the cloud environment.

Can someone please explain how to specify a jdbc connection parameter (see [here](https://jdbc.postgresql.org/documentation/94/connect.html#connection-parameters) for the list) at the datasource level i.e. when configuring the datasource?

**Comment by balteo** [comment]
@scottfrederick 

Hi Scott,

Can you please let me know whether this is a bug? 

Isn't `ConnectionConfig` meant for passing JDBC connection parameters?

Thanks in advance,

**Comment by balteo** [comment]
@ramnivas @scottfrederick 

Hi,

I noticed that [`DataSourceConfigurer#configureConnection()`](https://github.com/spring-cloud/spring-cloud-connectors/blob/a6d19e86d1f5eab9e95b73af7749ea6924ec8315/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/service/relational/DataSourceConfigurer.java#L36) does not set the passed `currentSchema=application` connection parameter.

Is there any way of passing those JDBC connection parameters at the `DataSource` level using the SCC API?

**Comment by scottfrederick** [comment]
@balteo Connectors doesn't provide a way to customize the JDBC connection string used to connect to the database. It is assumed that the service instance that Connectors is reading from (managed by a broker or a user-provided service instance) contains the necessary connection string in the service credentials. 

The configuration provided by Connectors via `DataSourceConfig`, `ConnectionConfig`, and `PoolConfig` configure the `DataSource` bean that is created by Connectors, not the connection string. In this example, there would need to be a `currentSchema` field on the `DataSource` bean with the proper setter in order for the parameter to get set the way you are expecting it to. Whether that's possible or not depends on the concrete `DataSource` implementation. 

It would be possible to create a custom extension to [`PostgresServiceInfoCreator`](https://github.com/spring-cloud/spring-cloud-connectors/blob/6f1b17d12d03bbfa89e4e4daa4b9460c416e846f/spring-cloud-cloudfoundry-connector/src/main/java/org/springframework/cloud/cloudfoundry/PostgresqlServiceInfoCreator.java) to manipulate the jdbcUrl if the service instance isn't provide enough information in the credentials.
