### ISSUE TITLE
Drop support for Commons DBCP

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud/spring-cloud-connectors#180]
Spring Boot 2.0 will drop support for Commons DBCP. Perhaps Spring Cloud Connectors could do the same as part of its Spring Framework 5-based release?

**Comment by scottfrederick** [comment]
Thanks Andy, I'll take a look at that. I'm getting ready to do a round of maintenance on Connectors so this is timely.

**Comment by scottfrederick** [comment]
Fixed via 70a6f714962877bc59e4b86b37a444859bfb18e7
