### ISSUE TITLE
NullPointerException with empty credentials

### ISSUE THREAD

**Issue by CAFxX** [spring-cloud/spring-cloud-connectors#183]
We're getting a NullPointerException in https://github.com/spring-cloud/spring-cloud-connectors/blob/93631a26676c3afab09d2eac20b342bebb513363/spring-cloud-cloudfoundry-connector/src/main/java/org/springframework/cloud/cloudfoundry/CloudFoundryServiceInfoCreator.java#L65 because one of our service brokers doesn't return the optional (see https://docs.cloudfoundry.org/services/api.html#binding-types) `credentials` key.

If `credentials` is null that function should return false instead of throwing an exception. The fix is trivial but unfortunately we haven't signed the CLA so we can't provide a PR.

**Comment by scottfrederick** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-connectors/commit/eff000d30fc5e32c0c75653b0d4965f5634b80eb
