### ISSUE TITLE
Change size of connection pool

### ISSUE THREAD

**Issue by daniel-bub** [spring-cloud/spring-cloud-connectors#184]
Hi,

I'm looking for means to change the size of the connection pool being used for DB2 data sources.
I stepped through the code and found the value only to be statically assigned.

In file [DbcpLikePooledDataSourceCreator](https://github.com/spring-cloud/spring-cloud-connectors/blob/2d763feb82f67d97f5837f5441f955294c7489fb/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/service/relational/DbcpLikePooledDataSourceCreator.java#L40) the default values are set.
However I didn't find any means to change this behavior. In all cases the serviceConnectorConfig is null.

BR Daniel

**Comment by scottfrederick** [comment]
@daniel-bub You can provide a `PoolConfig` to change the size of the connection pool as in this example from the [docs](http://cloud.spring.io/spring-cloud-connectors/spring-cloud-spring-service-connector.html#_relational_database_db2_mysql_oracle_postgresql_sql_server): 

```
@Bean
public DataSource dataSource() {
    PoolConfig poolConfig = new PoolConfig(5, 30, 3000);
    DataSourceConfig dbConfig = new DataSourceConfig(poolConfig, null);
    return connectionFactory().dataSource("my-own-personal-sql", dbConfig);
}
```
