### ISSUE TITLE
Add Redis Sentinel Support

### ISSUE THREAD

**Issue by markbigler** [spring-cloud/spring-cloud-connectors#185]
Is there any plan to extend `RedisServiceInfo`, `RedisServiceInfoCreator` and `RedisConnectionFactoryCreator` with master/sentinel properties?

**Comment by scottfrederick** [comment]
@markbigler This is the first request we've had to add this. Can you provide an example of what the credentials would look like on one of the supported clouds for a Redis service that provided master/sentinel credentials?

**Comment by markbigler** [comment]
@scottfrederick On a cloud foundry based cloud the credentials for a (high available) redis service looks like:
```{
  "VCAP_SERVICES": {
    "redisent": [
      {
        "credentials": {
          "master": "redis://aaaaaaaa-bbbb-aaaa-bbbb-aaaaaaaaaaaa",
          "password": "...",
          "sentinels": [
            {
              "host": "aaaaaaaa-bbbb-aaaa-bbbb-aaaaaaaaaaaa-2.service.consul",
              "port": 1234
            },
            {
              "host": "aaaaaaaa-bbbb-aaaa-bbbb-aaaaaaaaaaaa-1.service.consul",
              "port": 1234
            },
            {
              "host": "aaaaaaaa-bbbb-aaaa-bbbb-aaaaaaaaaaaa-0.service.consul",
              "port": 1234
            }
          ],
          "servers": [
            {
              "host": "aaaaaaaa-bbbb-aaaa-bbbb-aaaaaaaaaaaa-2.service.consul",
              "port": 2345
            },
            {
              "host": "aaaaaaaa-bbbb-aaaa-bbbb-aaaaaaaaaaaa-1.service.consul",
              "port": 2345
            },
            {
              "host": "aaaaaaaa-bbbb-aaaa-bbbb-aaaaaaaaaaaa-0.service.consul",
              "port": 2345
            }
          ],
          "host": "aaaaaaaa-bbbb-aaaa-bbbb-aaaaaaaaaaaa-master.service.consul",
          "port": 2345
        },
        ...
      }
    ]
  }
}
```

Some additional information on how to deal with redis sentinel:
- http://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis:sentinel
- https://github.com/spring-projects/spring-data-examples/tree/master/redis/cluster-sentinel

**Comment by nisheethagarwal** [comment]
I face a similar issue but the VCAP structure for my Redis instance is different than the one posted here.

```
"redis": [
			{
				"credentials": {
					"password": "...",
					"redis_nodes": [
						{
							"hostname": "xx.xx.xx.xxx",
							"port": "xxxx"
						},
						{
							"hostname": "xx.xx.xx.xxx",
							"port": "xxxx"
						},
						{
							"hostname": "xx.xx.xx.xxx",
							"port": "xxxx"
						}
					],
					"sentinel_nodes": [
						{
							"hostname": "xx.xx.xx.xxx",
							"port": "xxxxx"
						},
						{
							"hostname": "xx.xx.xx.xxx",
							"port": "xxxxx"
						},
						{
							"hostname": "xx.xx.xx.xxx",
							"port": "xxxxx"
						}
					],
					"uri": "redis-sentinel://a:b@xx.xx.xx.xxx:xxxxx,xx.xx.xx.xxx:xxxxx,xx.xx.xx.xxx:xxxxx#mymaster"
				},
				...
			}
		]
```

**Comment by scottfrederick** [comment]
Thanks @nisheethagarwal, this is helpful. 

One of the goals of `spring-cloud-cloudfoundry-connector` is to "normalize" the information provided in `VCAP_SERVICES` from different service brokers into a common data model that can be consumed by apps and used in the Spring service bean creation logic in `spring-cloud-spring-service-connector`. 

These two examples look similar in structure, with different names for the fields (`sentinels` and `servers` vs `sentinel_nodes` and `redis_nodes`). I'm not sure about the difference between `"master": "redis://aaaaaaaa-bbbb-aaaa-bbbb-aaaaaaaaaaaa"` and `"uri": "redis-sentinel://a:b@xx.xx.xx.xxx:xxxxx,xx.xx.xx.xxx:xxxxx,xx.xx.xx.xxx:xxxxx#mymaster"`. 

The work involved for this would be: 

- [ ] add sentinel-related fields to `RedisServiceInfo` in `spring-cloud-core`
- [ ] add parsing of sentinel-related fields to `RedisServiceInfoCreator` in `spring-cloud-cloudfoundry-connector`, recognizing several possible names for the fields
- [ ] modify `RedisConnectionFactoryCreator` in `spring-cloud-spring-service-connector` to use sentinel-related fields in the Spring Data Redis connection factory setup

**Comment by anwarchk** [comment]
@scottfrederick I can pick this up if no one else called dibs on it :-)

**Comment by ljheric** [comment]
Is there any update for this functionality? When will it available in the spring-cloud-connectors?

**Comment by ljheric** [comment]
@scottfrederick Is there any update for this functionality? When will it available in the spring-cloud-connectors? Thank you!

**Comment by scottfrederick** [comment]
@siimp @ljheric There are no immediate plans to add this feature to Spring Cloud Connectors. I'd be happy to provide some guidance and and assistance to anyone who wants to contribute a solution.

**Comment by markpollack** [comment]
Contributions are welcome in the https://github.com/pivotal-cf/java-cfenv project as  Spring Cloud Connectors are now in maint mode only.  There is already an issue for this in that repo - https://github.com/pivotal-cf/java-cfenv/issues/32

The JSON structures look to be very different.  Are these coming from a product or are they a home made tile?
