### ISSUE TITLE
 DB2DataSourceCreator - validation query does not work with DB2 on ZOS 

### ISSUE THREAD

**Issue by ap1256** [spring-cloud/spring-cloud-connectors#187]
I am connecting to DB2 database on mainframe. It does not support the default validationQuery - "values 1"
As such every 4th call fails. There is no way to turn of the validation either. I tried setting the testOnBorrow property to false. Did not help.

public class DB2DataSourceCreator extends DataSourceCreator {

private static final String[] DRIVERS = new String[]{"com.ibm.db2.jcc.DB2Driver"};
private static final String VALIDATION_QUERY = "VALUES 1";

public DB2DataSourceCreator() {
	super("spring-cloud.db2.driver", DRIVERS, VALIDATION_QUERY);
}

}
Values 1 does not work on mainframe DB2. I get 'THE SQL STATEMENT IS NOT SUPPORTED. SQLCODE=-142, SQLSTATE=42612, DRIVER=3.64.106 SQL Code: -142, SQL State: 42612'

I did try adding the environment property spring.datasource.tomcat.validation-query but that did not help. 
I use this one. Which works on both versions of DB2 - AIX, Linux and mainframe. I didn't test with UDB.
SELECT 1 FROM sysibm.sysdummy1
My sample code attached
[jdbctemplate-withCloudConnector.zip](https://github.com/spring-cloud/spring-cloud-connectors/files/750531/jdbctemplate-withCloudConnector.zip)

**Comment by scottfrederick** [comment]
@ap1256 You can customize the validation query with code like this: 

```
@Configuration
class DataSourceConfig extends AbstractCloudConfig {
    @Bean
    public DataSource dataSource() {
        Map<String, Object> properties = new HashMap<String, Object>();
        properties.put("validationQuery", "SELECT 1 FROM sysibm.sysdummy1");
        properties.put("testOnBorrow", false);
        DataSourceConfig serviceConfig = new DataSourceConfig(properties);
        return connectionFactory().dataSource(serviceConfig);
    }
}
```

**Comment by ap1256** [comment]
thank you! that resolves the issue.
