### ISSUE TITLE
Upgrade Hikari dependency to align with new Java 8 baseline

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud/spring-cloud-connectors#188]
Spring Framework 5, Spring Boot 2.0, and Spring IO Platform Cairo will all require Java 8. As part of this, Spring Boot 2.0 (and therefore IO Platform Cairo) has moved from `HikariCP-java6` 2.3.13 to `HikariCP` 2.5.1. To ensure compatibility and align with the dependency management in Boot and the Platform, can you please upgrade your Hikari dependency accordingly?

More generally, this change probably fits in a 2.0 release of Spring Cloud Connectors that upgrades dependencies across the board. I'd expect upgrades to Spring Framework 5, Spring Data Kay, etc.

**Comment by scottfrederick** [comment]
Fixed via 43d80732569a1e49628e87aa78796eff95a0405b
