### ISSUE TITLE
Rename core module

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud/spring-cloud-connectors#189]
The core module is currently named `spring-cloud-core`, but should be `spring-cloud-connectors-core`.

**Comment by spencergibb** [comment]
Wonder if for 2.0 we change the group id as well (if it's not already)

**Comment by scottfrederick** [comment]
@spencergibb Are you suggesting something like `org.springframework.cloud.connectors` as a group ID?

**Comment by spencergibb** [comment]
@scottfrederick yes. Should I open a new issue?

**Comment by scottfrederick** [comment]
@spencergibb We can keep the discussion in this issue. 

I don't see other projects that qualify the `org.springframework.cloud` group ID with another segment in the name. Is there precedent for this, or has there been discussion about segmenting the namespace?

**Comment by spencergibb** [comment]
True. Now that I think of it, I think I was thinking of the actual java package.

**Comment by scottfrederick** [comment]
Fixed via 55701034d0af05e97442833727909ea65526fbdf
