### ISSUE TITLE
Support Google Cloud SQL on GCP

### ISSUE THREAD

**Issue by cah-andrewfitzgerald** [spring-cloud/spring-cloud-connectors#191]
[Google Cloud SQL](https://cloud.google.com/sql/docs/) is a managed mysql database available on Google Cloud Platform.  It is available to Cloud Foundry via the [Cloud Foundry Service Broker for Google Cloud Platform](https://github.com/GoogleCloudPlatform/gcp-service-broker).

It would be nice if Spring Cloud Cloud Foundry Connector were able to automatically configure connections for bound service instances.

**Comment by scottfrederick** [comment]
@cah-andrewfitzgerald Looking at the credentials shown under `CloudSQL` in the [GCP service broker docs](https://github.com/GoogleCloudPlatform/gcp-service-broker#use), the credentials for a bound service include a `uri` field with a `mysql` scheme. This should be enough for Connectors to detect and configure a MySQL connection per the [detection criteria](http://cloud.spring.io/spring-cloud-connectors/spring-cloud-cloud-foundry-connector.html#_mysql). 

Do you have an example of the full `VCAP_SERVICES` environment variable that includes a GCP CloudSQL binding that you can share (with password and other sensitive data redacted)?

**Comment by cah-andrewfitzgerald** [comment]
```
"google-cloudsql": [
        {
          "credentials": {
            "CaCert": "-----BEGIN CERTIFICATE-----\nMII...snip...nA==\n-----END CERTIFICATE-----",
            "ClientCert": "-----BEGIN CERTIFICATE-----\nMIIDY...snip...jXw==\n-----END CERTIFICATE-----",
            "ClientKey": "-----BEGIN RSA PRIVATE KEY-----\nM...snip...eviA=\n-----END RSA PRIVATE KEY-----",
            "Password": "1...snip...=",
            "Sha1Fingerprint": "b4b...snip...922",
            "Username": "dcbe...snip...",
            "database_name": "pcf-sb-11-...snip....",
            "host": "104snip...",
            "instance_name": "pcf-sb-10-...snip...",
            "last_master_operation_id": "90590a35-...snip...",
            "uri": "mysql://dcbe...snip...:1x...snip...%3D@104.198.50.189/pcf-sb-11-...snip...?ssl_mode=required"
          },
          "syslog_drain_url": null,
          "volume_mounts": [],
          "label": "google-cloudsql",
          "provider": null,
          "plan": "basic",
          "name": "cloudsql",
          "tags": [
            "gcp",
            "cloudsql"
          ]
        }
      ]
```

**Comment by cah-andrewfitzgerald** [comment]
```{  
   "google-cloudsql":[  
      {  
         "credentials":{  
            "CaCert":"-----BEGIN CERTIFICATE-----\nM...snip...==\n-----END CERTIFICATE-----",
            "ClientCert":"-----BEGIN CERTIFICATE-----\nM...snip...w==\n-----END CERTIFICATE-----",
            "ClientKey":"-----BEGIN RSA PRIVATE KEY-----\n...snip...A=\n-----END RSA PRIVATE KEY-----",
            "Password":"1...snip...c=",
            "Sha1Fingerprint":"b...snip...2",
            "Username":"d...snip...d",
            "database_name":"p...snip...9",
            "host":"104...snip...",
            "instance_name":"p...snip...4",
            "last_master_operation_id":"90590a35-...snip...",
            "uri":"mysql://d...snip...d:1...snip...c%3D@104.198.50.189/p...snip...9?ssl_mode=required"
         },
         "syslog_drain_url":null,
         "volume_mounts":[  

         ],
         "label":"google-cloudsql",
         "provider":null,
         "plan":"basic",
         "name":"cloudsql",
         "tags":[  
            "gcp",
            "cloudsql"
         ]
      }
   ]
}```

**Comment by cah-andrewfitzgerald** [comment]
I detailed some of the issues I've been having in GoogleCloudPlatform/gcp-service-broker#108, a coworker and I have been messing around with it for a while and have no idea how to bind a boot app to Cloud SQL on PCF in GCP.

Unfortunately our loggregator endpoint is failing, and the stacktrace is too long to see the root cause in the app manager.  But we've tried a combination of jdbc url options and can't seem to get it to connect

**Comment by scottfrederick** [comment]
@cah-andrewfitzgerald Any progress in getting the GCP broker team to assist with an example of configuring a Java app to use the provided Google Cloud SQL service? 

The `CaCert`, `ClientCert`, `ClientKey`, `Sha1Fingerprint` and `last_master_operation_id` fields in the credentials shown above are not typical with other MySQL service offerings. If these are required to be used in some way by the app bound to the Cloud SQL service then we'll need to know now they are expected to be used so we can figure out if we can adapt the existing MySQL service connector or if we'll need a new service connector specifically for Cloud SQL.

**Comment by cah-andrewfitzgerald** [comment]
I've been meaning to take another stab on it, but our GCP PCF instance is the ops playground, waiting on them to spin it back up and get the broker reinstalled

**Comment by scottfrederick** [comment]
For an alternative to using Spring Cloud Connectors to consume a Google Cloud SQL service, see https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql.

**Comment by scottfrederick** [comment]
@cah-andrewfitzgerald It appears that Google Cloud SQL needs to be handled differently from other common cloud SQL providers (e.g. MySQL and PostgreSQL). It has been suggested that support for this should be added to the [Spring Cloud GCP](https://github.com/spring-cloud/spring-cloud-gcp) project as a `spring-cloud-gcp-connectors` extension project, instead of trying to fit this into core Connectors. I'm going to close this issue in favor of that approach, please comment or re-open if you'd like to discuss adding it to core Connectors instead.
