### ISSUE TITLE
Autoconfiguration's sensible default for connection pool needs better override hook

### ISSUE THREAD

**Issue by stackspring** [spring-cloud/spring-cloud-connectors#192]
Right now after deploying spring boot application on CF, it just assigns 4 connection pools, see below links. If we have to override we have to extend AbstractCloudConfig which disables rest of the auto configuration. If we have alternative please provide that solution.

(https://discuss.pivotal.io/hc/en-us/articles/221898227-Connection-pool-warning-message-maxIdle-is-larger-than-maxActive-setting-maxIdle-to-4-seen-in-PCF-deployed-Spring-app)

https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/service/relational/DbcpLikePooledDataSourceCreator.java

http://stackoverflow.com/questions/42545645/cloud-foundry-spring-boot-data-source-pool-configuration

**Comment by scottfrederick** [comment]
There isn't currently an alternative. If you need to override the default pool settings, you'll need to provide all service configuration.
