### ISSUE TITLE
Redis cloud connector docs claims it supports uris, it doesn't

### ISSUE THREAD

**Issue by dshields-pivotal** [spring-cloud/spring-cloud-connectors#194]
The Spring Cloud Foundry Connector docs claims Redis connector supports uris:

http://cloud.spring.io/spring-cloud-connectors/spring-cloud-cloud-foundry-connector.html#_redis

but the connector class does not.  It only reads from single uri property, not from uris list property.

**Comment by scottfrederick** [comment]
Fixed via cbb70e726496dd8eccb14188c0fe79ab5296234c
