### ISSUE TITLE
Cloud connectors to connect DB2 using 2-way SSL 

### ISSUE THREAD

**Issue by gocooljan01** [spring-cloud/spring-cloud-connectors#198]
Hi , i am using the cloud connectors for DB2 connection  , but my DB2 is 2-way SSL , can any one tell me how we can configure 2-way SSL using Cloud Connectors .

If i use `cloudFactory.getCloud().getServiceConnector(dbServiceName, DataSource.class, dataSourceConfig)` with out 2-way SSL working fine. But when i enable the 2-way SSL for DB its not working.
 
Is there any way Cloud Connectors support 2-way SSL , so that i can configure .

Thanks

**Comment by scottfrederick** [comment]
@gocooljan01 This isn't possible currently. It will require an enhancement to Connectors. 

Can you give more information about the cloud platform that is providing the DB2 with 2-way SSL enabled? Is it a public Cloud Foundry platform like Pivotal Web Services or IBM BlueMix, or is it a private/internal Cloud Foundry deployment? 

Are the service credentials being provided by a service broker? If so, please share an example of a `VCAP_SERVICES` environment variable for an app that is bound to the DB2 service (with sensitive credentials redacted if necessary).

**Comment by scottfrederick** [comment]
Another note: service brokers with requirements like SSL can provide a custom JDBC connection string in a `jdbcUrl` field in the credentials of a Cloud Foundry service instance. That `jdbcUrl` connection string can include additional flags required for connection that can't easily be provided when only a `uri` field or discrete host, port, database, username, password, etc fields are created. 

Closing this issue unless additional information can be provided on service brokers that require SSL connections.
