### ISSUE TITLE
Is there a way to supply additional JDBC properties?

### ISSUE THREAD

**Issue by chrylis** [spring-cloud/spring-cloud-connectors#202]
I'm trying to get PostgreSQL native enum types working with Hibernate, and the most straightforward solution is to set the `stringtype=unspecified` property on the JDBC connection (to make the server infer the enum type for the column). However, the JDBC URI is being provided in my VCAP, and the `DataSource` (and pool) by Connectors. I know there's the `MapServiceConnectorConfig`, but IIRC there's no hook to add custom entries to it.

Is there any way to insert additional properties to be set on the JDBC `DataSource` created by Connectors?

**Comment by scottfrederick** [comment]
@chrylis There are three types of configuration that can be supplied when customizing the `DataSource` created by Connectors. When using Java configuration like this: 

```
@Bean
public DataSource dataSource() {
    PoolConfig poolConfig = new PoolConfig(5, 30, 3000);
    
    ConnectionConfig connConfig = new ConnectionConfig("useUnicode=yes;characterEncoding=UTF-8");
    
    Map<String, Object> properties = new HashMap<String, Object>();
    properties.put("driverClassName", "test.driver");
    properties.put("validationQuery", "test validation query");
    properties.put("testOnBorrow", false);
    
    DataSourceConfig dbConfig = new DataSourceConfig(poolConfig, connConfig, properties);
    return connectionFactory().dataSource("my-own-personal-sql", dbConfig);
}
```

the `DataSource` will be configured as follows: 

* `PoolConfig` will be used to set well-known properties on the `DataSource` bean related to connection pools (min pool size, max pool size, max wait time). Connectors knows the names of the properties for each concrete `DataSource` implementation (Apache Commons DBCP and DBCP2, Tomcat JBCP Pool, HikariCP) and sets the appropriate properties from this object. 
* `ConnectionConfig` will be used to set the value of a `connectionProperties` property on a concrete `DataSource` object that supports this property (Apache Commons DBCP and DBCP2, Tomcat JBCP Pool). See [Commons DBCP2](https://commons.apache.org/proper/commons-dbcp/apidocs/org/apache/commons/dbcp2/BasicDataSource.html#setConnectionProperties-java.lang.String-) as an example. This string is typically passed on to the JDBC driver. 
* `Map<String, Object> properties` will be used to set properties on the concrete `DataSource` object. The keys in this map correspond to bean properties/setter methods on the `DataSource` object, and are specific to the concrete implementation being used. 

See `Detection and Prioritization of DataSource Implementations` in the [documentation](http://cloud.spring.io/spring-cloud-connectors/spring-cloud-spring-service-connector.html#_relational_database_db2_mysql_oracle_postgresql_sql_server) for details on how a concrete `DataSource` implementation is chosen. 

It looks to me like `ConnectionConfig` is what you need, but I can't say for sure. 

The documentation should include this level of detail. I've created #203 to address that.

**Comment by chrylis** [comment]
As far as I remember (I was involved back around 1.1), the JavaConfig you showed has to live in an `extends AbstractCloudConfig` in order to have access to the `connectionFactory()` (which is loaded with the `ServiceInfo`s), and if I supply my own I have to include explicit `@Bean`s for every service I want bound--I can't simply add the `DataSource` override and have everything else still autocreated. Am I correct on this?

**Comment by scottfrederick** [comment]
> the JavaConfig you showed has to live in an extends `AbstractCloudConfig` in order to have access to the connectionFactory()

You can either extend `AbstractCloudConfig` and use `connectionFactory().dataSource(...);` or you can avoid extending `AbstractCloudConfig` and create the necessary beans yourself - something like: 

```
@Configuration
@Profile("cloud")
public class DataSourceConfiguration {
  @Bean
  public Cloud cloud() {
    return new CloudFactory().getCloud();
  }

  @Bean
  @ConfigurationProperties(DataSourceProperties.PREFIX)
  public DataSource dataSource() {
    ....
    DataSourceConfig dbConfig = new DataSourceConfig(poolConfig, connConfig, properties);
    return cloud.getSingletonServiceConnector(DataSource.class, dataSourceConfig)
  }
}
```

> if I supply my own I have to include explicit `@Beans` for every service I want bound

Unfortunately, that's still true - auto-configuration is all-or-nothing.

**Comment by scottfrederick** [comment]
@chrylis I'm going to close this issue since it's been inactive for a while. Feel free to re-open if there's something you'd like to see done on this.
