### ISSUE TITLE
Clarify DataSource configuration options in documentation

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud/spring-cloud-connectors#203]

**Comment by scottfrederick** [comment]
see https://github.com/spring-cloud/spring-cloud-connectors/issues/202#issuecomment-302137691

**Comment by jvmlet** [comment]
@scottfrederick , is it possible to specify the connection pool settings via envioment variable  for 3rd party aplication that uses the service conenctor (in my cases it's Spring cloud data flow)?

**Comment by scottfrederick** [comment]
@jvmlet Connectors doesn't support configuration via environment properties. Apps or libraries using Connectors need to provide such configuration options themselves and invoke Connectors Java configuration as appropriate. 

In the case of Spring Cloud Data Flow, @markpollack is addressing this in https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/415. Let's keep ongoing discussion of the solution in that issue.

**Comment by jvmlet** [comment]
@scottfrederick, the https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/issues/415 is closed.

**Comment by scottfrederick** [comment]
I believe @markpollack is doing some additional work to support configuration via Data Flow-specific properties. Please continue the discussion in the Data Flow repository as this instead of in this issue that is meant to cover changes to Connectors documentation.

**Comment by sabbyanandan** [comment]
@jvmlet: I clarified what worked and not, and what we are fixing already in [Gitter](https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5b17df0282a4d36ea6d5246e) earlier today. It'd be great if you can avoid duplicate discussion on the same topic - one less item for everyone.
