### ISSUE TITLE
MongoLab environment variable changed to MONGODB_URI

### ISSUE THREAD

**Issue by rob-baily** [spring-cloud/spring-cloud-connectors#204]
Per the current information at https://devcenter.heroku.com/articles/mongolab the current env variable for MongoLab is now MONGODB_URI.  This should be added to the list of environment variables and documentation at http://cloud.spring.io/spring-cloud-connectors/spring-cloud-heroku-connector.html#_mongodb_mongolab_mongohq_mongosoup.

**Comment by hosuaby** [comment]
I opened a PR#209 for this feature

**Comment by scottfrederick** [comment]
Fixed via PR #209
