### ISSUE TITLE
Make Tags.contains() case-insensitive

### ISSUE THREAD

**Issue by geezhawk** [spring-cloud/spring-cloud-connectors#205]
One of our custom Cloud Foundry services is tagged with an uppercase R `Redis`, and as a result it isn't being picked up by auto-reconfiguration, which matches only lowercase tags. Changing the tag string to lowercase in [`Tags.contains()`](https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-cloudfoundry-connector/src/main/java/org/springframework/cloud/cloudfoundry/Tags.java) before checking against the list of relevant tags would prevent this type of bug and make the auto-reconfiguration process a little more robust for users with different conventions for naming tags. 

Let me know if this sounds like a worthwhile change and I'll submit a PR.

**Comment by scottfrederick** [comment]
I think this is reasonable. A PR would be welcomed.

**Comment by scottfrederick** [comment]
Fixed via 5896a0b8b15f1206b19420cf43c36290369a416c
