### ISSUE TITLE
RelationalServiceInfo.buildJdbcUrl incorrect when userName == null and password != null

### ISSUE THREAD

**Issue by jondavidnd1** [spring-cloud/spring-cloud-connectors#207]
This is a minor bug that can be worked around by providing a jdbcUrl in the constructor, but I don't think the logic in RelationalServiceInfo.formatQuery agrees with the logic in RelationalServiceInfo.formatUserinfo.

Current Code:

```java
private String formatUserinfo() {
  if (getUserName() != null && getPassword() != null) {
    return String.format("?user=%s&password=%s", getUserName(), getPassword());
  }
  if (getUserName() != null) {
    return String.format("?user=%s", getUserName());
  }
  return "";
}

private String formatQuery() {
  if (getQuery() != null) {
    if (getUserName() == null && getPassword() == null) {
      return String.format("?%s", getQuery());
    } else {
      return String.format("&%s", getQuery());
    }
  }
  return "";
}
```

If `getUserName() == null` and `getPassword() != null` then `formatUserinfo()` will return an empty string, but `formatQuery()` will return the query with an `&` prepended instead of a `?`.

I think `formatQuery` should be changed to:

```java
private String formatQuery() {
  if (getQuery() != null) {
    if (getUserName() == null) {  //removed '&& getPassword() == null'
      return String.format("?%s", getQuery());
    } else {
      return String.format("&%s", getQuery());
    }
  }
  return "";
}
```

**Comment by scottfrederick** [comment]
Fixed via eaa53f8cd6e4629a85c914442e7bf05019215d79 @scottfrederick scottfrederick committed 20 seconds ago

@jondavidnd1 I'm not sure how you got a username without a password, as this causes an exception when parsing the URL, but this change does address the inconsistency you pointed out.
