### ISSUE TITLE
Unable to detect amazon RDS service using Spring cloud connectors core library in cloud foundry

### ISSUE THREAD

**Issue by anupz** [spring-cloud/spring-cloud-connectors#210]
I have a simple java application (not spring one) that wanted to get amazon RDS database parameters from cloud foundry env variable VCAP_SERVICES. I am using the following code but unable to access any of the databases.

I am trying one of the sample code provided on library home page.

**Cloud foundry application log**: 
```
2017-08-28T14:15:44.952-07:00 [APP/PROC/WEB/0] [ERR] WARNING: No suitable service info creator found for service employee-maria-rds. Did you forget to add a ServiceInfoCreator?
2017-08-28T14:15:44.952-07:00 [APP/PROC/WEB/0] [ERR] Aug 28, 2017 9:15:44 PM org.springframework.cloud.AbstractCloudConnector getServiceInfo
```

Java application :
```
public class App {
    public static void main (String args[]) throws InterruptedException, SQLException {
        CloudFactory cloudFactory = new CloudFactory();
        Cloud cloud = cloudFactory.getCloud();
        // ServiceInfo has all the information necessary to connect to the underlying service
        List<ServiceInfo> serviceInfos = cloud.getServiceInfos();
        for (ServiceInfo serviceInfo : serviceInfos) {
            if (serviceInfo instanceof RelationalServiceInfo) {
                System.out.println(((RelationalServiceInfo) serviceInfo).getJdbcUrl());
            }
}}}
```
Above code will print nothing.

**Cloud Foundry Env Variables:**
```
{
  "staging_env_json": {},
  "running_env_json": {},
  "system_env_json": {
    "VCAP_SERVICES": {
      "mariaDB": [
        {
          "credentials": {
            "uri": "jdbc:mysql://db1.us-east-1.rds.amazonaws.com:3306/employee",
            "username": "xxxx",
            "password": "xxxx",
            "host": "db1.us-east-1.rds.amazonaws.com",
            "port": "3306",
            "database": "employee"
          },
          "syslog_drain_url": null,
          "volume_mounts": [],
          "label": "mariaDB",
          "provider": null,
          "plan": "Medium-Plan",
          "name": "employee-maria-rds",
          "tags": []
        },
        {
          "credentials": {
            "uri": "jdbc:mysql://db2.us-east-1.rds.amazonaws.com:3306/hcm",
            "username": "xxxx",
            "password": "xxxx",
            "host": "db2.us-east-1.rds.amazonaws.com",
            "port": "3306",
            "database": "hcm"
          },
          "syslog_drain_url": null,
          "volume_mounts": [],
          "label": "mariaDB",
          "provider": null,
          "plan": "Small-Plan",
          "name": "hcm-maria-db",
          "tags": []
        }
      ]
    }
  },
  "application_env_json": {
    "VCAP_APPLICATION": {
      "cf_api": "https://apps.abc.com",
      "limits": {
        "fds": 16384,
        "mem": 256,
        "disk": 256
      },
      "application_name": "java-main-application",
      "application_uris": [],
      "name": "java-main-application",
      "space_name": "development",
      "space_id": "a8844960-4d08-4d80-b589-4ea1473ed0bb",
      "uris": [],
      "users": null,
      "application_id": "004sdf3ef-3d7a-44d6-81d5-a04bwetf62e07",
      "version": "c31234g56-4f42-4454-b30e-540sdghh684d6",
      "application_version": "d2ggd656-4f42-4434-b30e-54g2348684d6"
    }
  }
}
```
**pom.xml:**
```
 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-cloudfoundry-connector</artifactId>
            <version>1.2.4.RELEASE</version>
        </dependency>
```

**Comment by scottfrederick** [comment]
@anupz The likely cause is that the `credentials.uri` field is malformed. Per the [documentation](http://cloud.spring.io/spring-cloud-connectors/spring-cloud-cloud-foundry-connector.html#_mysql), Connectors will detect a MySQL service if it finds a `uri` field that starts with `mysql:` or a `jdbcUrl` field that starts with `jdbc:mysql:`. You credentials has `uri: jdbc:mysql://...`, which doesn't match either of those criteria. 

If service brokers provide a `uri` field in binding credentials, that field should be a platform-independent URI that can be consumed by any language/runtime (i.e. not Java specific). See the [Cloud Foundry docs](http://docs.cloudfoundry.org/services/binding-credentials.html) for more details. A `jdbcUrl` field can also be provided in the binding credentials if it is desirable or necessary to provide a separate JDBC connection string for Java applications. 

Is this `mariaDB` services info coming from a service broker? If so, what service broker?

**Comment by anupz** [comment]
Thanks @scottfrederick  for looking into the issue. 
 This is `mariaDB` services coming from aws rds service broker. Do you think we need to update `credentials.uri ` field to follow the standard or rename it to `jdbcUrl `, if we can?

**Comment by scottfrederick** [comment]
If you provide `credentials.uri` but change it to follow the convention suggested in the CF docs, then it will be usable by most languages/runtimes like Ruby, Node.js, Go, etc. Connectors will convert it to a JDBC URL when needed. If you only provide `credentials.jdbcUrl` then only Java apps will be able to use the service.

**Comment by anupz** [comment]
I will test this once vcap_services is updated.
