### ISSUE TITLE
Add support for influxdb

### ISSUE THREAD

**Issue by s-bortolussi** [spring-cloud/spring-cloud-connectors#211]
Spring boot 2.0.0.M3 comes with the [support](https://docs.spring.io/spring-boot/docs/2.0.0.M3/reference/htmlsingle/#boot-features-connecting-to-influxdb) of influxdb client autoconfiguration.

Could be nice to push connectivity further by adding an influxdb connector.

**Comment by scottfrederick** [comment]
@s-bortolussi The strategy with new connection types like this is to implement them in a Connectors extension project, not in the core Connectors project (especially connection types that don't have support in Spring Data). A separate extension project would seem to be appropriate for influxdb. I'll close this issue in favor of that approach, feel free to re-open if you want to discuss further.
