### ISSUE TITLE
RabbitMQ Port returns -1 for Spring app deployed to Cloud Foundry

### ISSUE THREAD

**Issue by anwarchk** [spring-cloud/spring-cloud-connectors#214]
I have a Spring app (non Spring Boot) that uses `XML` configuration and is using the `<cloud> namespace to access rabbit connection properties. The app is pushed to Cloud Foundry and is bound to a rabbit service instance. The issue I am facing is, even though `VCAP_SERVICES` for the app shows the the correct port under the `protocols` section, when I access the property  'cloud.services.myrabbit.connection.port', it returns `-1` as opposed to the value of `5672` as shown in the `VCAP_SERVICES`.

A sample app that demonstrate this problem is here : https://github.com/anwarchk/spring-mvc-vcap

VCAP env variable value is this : 
```{
  "p-rabbitmq": [
   {
    "credentials": {
     "hostname": "<redacted>",
     "hostnames": [
      "<redacted>",
      "<redacted>"
     ],
     "http_api_uri": "<redacted>",
     "http_api_uris": [
      "<redacted>"
     ],
     "password": "<redacted>",
     "protocols": {
      "amqp": {
       "host": "0.0.0.0",
       "hosts": [
        "0.0.0.0",
        "0.0.0.0"
       ],
       "password": "<redacted>",
       "port": 5672,
       "ssl": false,
       "uri": "amqp://<redacted>",
       "uris": [
        "amqp://<redacted>",
        "amqp://<redacted>"
       ],
       "username": "<redacted>",
       "vhost": "<redacted>"
      },
      "management": {
       "host": "<redacted>",
       "hosts": [
        "0000000000",
        "0000000000"
       ],
       "password": "<redacted>",
       "path": "/api/",
       "port": 15672,
       "ssl": false,
       "uri": "<redacted>",
       "uris": [
        "<redacted>",
        "<redacted>"
       ],
       "username": "<redacted>"
      }
     },
     "ssl": false,
     "uri": "amqp://<redacted>",
     "uris": [
      "amqp://<redacted>",
      "amqp:<redacted>"
     ],
     "username": "<redacted>",
     "vhost": "<redacted>"
    },
    "label": "p-rabbitmq",
    "name": "myrabbit",
    "plan": "standard",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "rabbitmq",
     "messaging",
     "message-queue",
     "amqp",
     "stomp",
     "mqtt",
     "pivotal"
    ],
    "volume_mounts": []
   }
  ]
 }
}
```

Properties exposed by `cloudProperties` bean. Some of the properties are omitted for brevity.

```
{
"cloud.services.myrabbit.connection.schemespecificpart":"//<redacted>",
"cloud.application.space_id":"6cd83348-30c0-4512-a99b-e02f3fe61345",
"cloud.services.rabbitmq.connection.host":"<redacted>",
"cloud.services.myrabbit.connection.port":"-1",
"cloud.services.rabbitmq.connection.uris":"[amqp://<redacted>]",
"cloud.services.rabbitmq.connection.scheme":"amqp",
"cloud.application.application_name":"spring-mvc-vcap",
"cloud.services.myrabbit.connection.uri":"<redacted>",
"cloud.services.myrabbit.id":"myrabbit",
"cloud.application.name":"spring-mvc-vcap",
"cloud.services.myrabbit.connection.host":"<redacted>",
"cloud.application.uris":"[spring-mvc-vcap-<redacted>]",
"cloud.services.rabbitmq.connection.port":"-1",
"cloud.application.app-id":"spring-mvc-vcap",
"cloud.services.myrabbit.connection.virtualhost":"e23494a9-c56e-4888-b152-e7a86b9accb2",
"cloud.services.rabbitmq.connection.path":"e23494a9-c56e-4888-b152-e7a86b9accb2",
"cloud.services.myrabbit.connection.uris":"[amqp://<redacted>]",
"cloud.services.myrabbit.connection.scheme":"amqp",
"cloud.application.application_version":"aca0b34e-7dc0-4868-b87d-e9ffc7df2ec7",
"cloud.services.rabbitmq.connection.password":"<redacted>",
"cloud.application.port":"8080",
"cloud.services.rabbitmq.connection.username":"<redacted>",
"cloud.application.space_name":"development",
"cloud.services.rabbitmq.id":"myrabbit"
}
```

**Comment by anwarchk** [comment]
@scottfrederick Created this issue to track our discussion on slack

**Comment by anwarchk** [comment]
@ramnivas any pointers ? Customer is waiting on this... thanks !

**Comment by scottfrederick** [comment]
@anwarchk Here's what's going on: if the credentials for the RabbitMQ service in `VCAP_SERVICES` contains a `uri` field, Connectors will parse that field into the individual components - scheme, host, port, and path (where path is mapped to `vhost`). In this case the `uri` has no port component, so you are seeing the `port` value as `-1`. The individual fields like `hostname`, `port`, `vhost`, etc are not parsed if a `uri` field is present. 

Essentially, the `-1` value means that the port was omitted from the `uri`, and the default RabbitMQ port `5672` should be used.

If you are trying to use the value `cloud.services.myrabbitmq.connection.port` from your example properties above in a SPEL expression in XML config, you should be able to use the ternary operator provided by SPEL to accomplish this defaulting. That might look something like this: 

```
<property name="rabbitPort" value="#{cloudProperties['cloud.services.myrabbit.connection.port'] == -1 ? 5672 : cloudProperties['cloud.services.myrabbit.connection.port']}"/>
```

**Comment by anwarchk** [comment]
@scottfrederick Thanks and I will try that. I am working on a PR where we would parse the `protocols` node and expose the connection port from there. Borrowed idea from Spring Boot's `CloudFoundryVcapEnvironmentPostProcessor`

**Comment by scottfrederick** [comment]
@anwarchk Keep in mind that the payload example you've shown is specific to Pivotal's `p-rabbitmq` service. Connectors supports parsing credentials from other RabbitMQ and AMQP service providers on other CF platforms. That's why the `VCAP_SERVICES` parsing is kept as simple as possible.

**Comment by scottfrederick** [comment]
@anwarchk Also, is it possible to just use the provided URI directly (e.g. `cloud.services.myrabbit.connection.uri`) instead of retrieving the constituent parts individually? Service providers sometimes include additional connection details and options in the full URI that aren't parsed into individual fields, so using the provided URI when possible is a good idea.

**Comment by anwarchk** [comment]
Customer has to pick and chose properties since they need to feed this to their Mule connection details. Otherwise it would have been a straight forward use of the auto configured connection factory. On your previous comment, it makes sense to me, but doesn't the same principle apply to Spring Boot, where in `CloudFoundryVcapEnvironmentPostProcessor` they parse the `protocols` node and makes it avaialble in `vcap.services...`

**Comment by scottfrederick** [comment]
Spring Boot does't really parse `VCAP_SERVICES` - it [converts the JSON structure to a flat map](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/cloud/CloudFoundryVcapEnvironmentPostProcessor.java). So the `vcap.services...` properties provided by Boot contain everything in the `VCAP_SERVICES` JSON, and it is up to the app to decide whether it wants to rely on specific fields in the flat map that may not be available from all service providers. Connectors uses a different approach, which is to normalize services payloads to a consistent form that helps apps be portable across cloud providers and service providers. 

A more general solution to providing the port value for use cases like yours would be to modify the URI parsing to set the explicit default value of `5672` when the port is not specified in the URI.

**Comment by anwarchk** [comment]
That makes sense, thanks for the clarification :-)

**Comment by scottfrederick** [comment]
Fixed via d4179cbd1d802cdf8911f276a66f10b4c71ceb08

@anwarchk I think this will address your use case. This change should be published in `1.2.5.BUILD-SNAPSHOT` in `repo.spring.io/lib-snapshot-local` in a few minutes if you'd like to test it.

**Comment by anwarchk** [comment]
@scottfrederick thanks for the quick turn around. I wanted to submit a PR, but this cool :-) I will give this a try now and will update here.

**Comment by anwarchk** [comment]
@scottfrederick just verified it and it works as expected. Thanks again !!!

**Comment by scottfrederick** [comment]
@anwarchk Glad to hear this works. I would have waited for a PR but I was in the middle of making a set of updates to this project in preparation for a release, and I wanted to get this change in before the release.
