### ISSUE TITLE
Replace instance_id with appliaction_id when reading properties from VCAP_APPLICATION  in ApplicationInstanceInfoCreater

### ISSUE THREAD

**Issue by jnbis** [spring-cloud/spring-cloud-connectors#225]
org.springframework.cloud.cloudfoundry.ApplicationInstanceInfoCreater reading the wrong property from the environment.

Looking at http://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-APPLICATION instance_id is no longer used, instead appliaction_id should be used.

This introduce an NPE in org.springframework.cloud.getAppProperties when running on cloud foundry.

**Comment by scottfrederick** [comment]
@jnbis Application identity and instance identity are different things. If you deploy an application and scale it to multiple instances, the app GUID and app name will be the same for all instances, but the instance GUID will be unique to each instance. 

In `ApplicationInstanceInfo`, `getAppId()` should provide an ID unique to the application, and `getInstanceId()` should provide an ID unique to the instance. I'm not sure when `instance_id` was removed from `VCAP_APPLICATION` JSON - I'm looking into when (and why) that was done. Connectors should not throw an NPE when either of those fields are absent, but the fix would be to have `getInstanceId()` simply return `null` if that value is not provided by the platform.
