### ISSUE TITLE
HikariCP ignores connection property "currentSchema"

### ISSUE THREAD

**Issue by matthjes** [spring-cloud/spring-cloud-connectors#226]
Hi,

I have the following datasource setup:

```
@Bean
@Primary
public DataSource dataSource() {
	Map<String, Object> connectionProperties = new HashMap<>();
	connectionProperties.put("currentSchema", "app_gateway");

	PoolConfig poolConfig = new PoolConfig(20, 80, 3000);
	ConnectionConfig connectionConfig = new ConnectionConfig("currentSchema=app_gateway");
	DataSourceConfig dataSourceConfig = new DataSourceConfig(poolConfig, connectionConfig, connectionProperties);
	return connectionFactory().dataSource(dataSourceConfig);
}
```
It seems like the connection property "curreentSchema" is not picked up by the HikariCP Connection Pool, because when I try to access a table of the schema "app_gateway" I'm getting an exception:

`nested exception is org.postgresql.util.PSQLException: ERROR: relation \"oauth_access_token\" does not exist`

The JDBC-URL also does not contain the property:

`jdbcUrl.........................jdbc:postgresql://svzpg99.intra.swm.de:5432/mplt_f479acb2_32b1_4ca3_ae44_d5934cd4957f?user=mpl_JJiYCECEBlbsBYlG&password=<masked>`

**Comment by scottfrederick** [comment]
@matthjes When a `Map<String, Object>` is provided in a `DataSourceConfig`, Connectors will attempt to set corresponding properties on the `DataSource` bean being created, following Java Bean conventions. Looking at [`HikariDataSource`](https://github.com/brettwooldridge/HikariCP/blob/master/src/main/java/com/zaxxer/hikari/HikariDataSource.java) and its subclass [`HikariConfig`](https://github.com/brettwooldridge/HikariCP/blob/master/src/main/java/com/zaxxer/hikari/HikariConfig.java), I don't see a `currentSchema` bean property on either. 

When a `ConnectionConfig` string is provided in a `DataSourceConfig`, Connectors will attempt to set a `connectionProperties` property on the `DataSource` bean. The [Apache DBCP](https://git-wip-us.apache.org/repos/asf?p=commons-dbcp.git;a=blob;f=src/main/java/org/apache/commons/dbcp2/BasicDataSource.java;hb=refs/heads/master#l1890) and Tomcat JDBC `DataSource` implementations have this `connectionProperties` property, but `HikariDataSource` does not.

Connectors will use a `jdbcUrl` value as-is from the service instance credentials, or build a JDBC URL from a `uri` or `url` field in credentials as necessary. It won't modify the JDBC connection string from properties provided when the `DataSource` is created. 

I'm not sure how to get the `currentSchema` value set automatically via Connectors configuration. You might need to explicitly call other methods of `HikariDataSource` once is is returned from Connectors, or issue an SQL query against the `DataSource`.

**Comment by scottfrederick** [comment]
The Spring Cloud Connectors project is [in maintenance mode](https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services), in favor of the newer [Java CFEnv](https://github.com/pivotal-cf/java-cfenv) project. If this feature is still desired, please [file an issue](https://github.com/pivotal-cf/java-cfenv/issues/new) in the Java CfEnv project.
