### ISSUE TITLE
AMQP Connection Factory automaticRecoveryEnabled Property

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-connectors#233]
Spring AMQP prefers this setting to be false (Spring AMQP has had its own recovery mechanism since day 1).

Over the years we have fixed corner cases where, when the setting is true, problems result because of conflicts with the built-in recovery.

Since 4.0, the rabbit client now sets this to true by default; Spring AMQP disables it by default, unless the connection factory is built externally.

Since the connectors project provides an "external" `com.rabbitmq.client.ConnectionFactory` it defeats Spring AMQP's default behavior.

Please consider setting this property to false when creating the factory. Also consider using the `RabbitConnectionFactoryBean` to create the factory (it will set the property to false by default).

**Comment by scottfrederick** [comment]
Fixed via #234
