### ISSUE TITLE
ReleationalServiceInfo issue

### ISSUE THREAD

**Issue by arumugham86** [spring-cloud/spring-cloud-connectors#237]
We are using Edgware and Spring 1.5.x and I noticed when I upgraded to Edgware.SR4 all the modules that connected to database started failing and upon couple of days of debugging found out that org.springframework.cloud.service.common.RelationalServiceInfo class had a recent change in 1.2.6.Release (works fine in 1.2.5.Release), where as part of url, User name and password are getting encoded and our password is also being encoded which happens to have a ! mark and wont connect thus.

Change was made in formatUserinfo() of that class.

Additional info (may be relavant)

We are connecting to external database from PCF using Userprovided service with a URI configured.

**Comment by scottfrederick** [comment]
@arumugham86 Spring Cloud Connectors isn't part of the Spring Cloud release train, so upgrading from one Edgware SR to another won't result in a different version of Connectors. 

Spring Boot can manage the Connectors version via `spring-boot-starter-cloud-connectors`. If you are using this starter and you upgraded the Boot version, that would explain how you got Connectors `1.2.6.RELEASE`. 

A workaround for this would be to configure Boot to use Connectors `1.2.5.RELEASE`. There is an explanation of how to override Boot-managed dependency versions here: https://spring.io/blog/2016/04/13/overriding-dependency-versions-with-spring-boot. 

Encoding the username and password fields was the result of several users reporting that special characters in usernames and/or passwords from a service broker wouldn't allow a connection. It sounds like you have the opposite problem. I think we're going to have to come up with a way to encode these values by default but allow a developer to override that default. I'll try to think of a way to do that cleanly.

**Comment by arumugham86** [comment]
Hello, Yes, I have done exactly that to our projects and still use (now) Edgware.SR5. Keep me posted on this, thanks!
