### ISSUE TITLE
Disable / Configure Automatic Security Binding

### ISSUE THREAD

**Issue by andresoviedo** [spring-cloud/spring-cloud-connectors#244]
I have a micro-service using this library for Discovery.  I don't want to secure application using Single Sign On.

https://cloud.spring.io/spring-cloud-cloudfoundry/1.1.x/

Is it possible to disable or configure the security auto-configuration?

**Comment by scottfrederick** [comment]
@andresoviedo Please clarify what client dependencies you are using, showing a maven or gradle snippet if possible. It's not clear whether you are using `org.springframework.cloud:spring-cloud-cloudfoundry`, `org.springframework.cloud:spring-cloud-cloudfoundry-connector`, or possibly `io.pivotal.spring.cloud:spring-cloud-services-*`.

**Comment by andresoviedo** [comment]
Hi.

**Comment by scottfrederick** [comment]
@andresoviedo It's not clear to me how Spring Security is getting pulled in with the dependencies above. However, given that Security is getting pulled in, the solution you [posted above](https://github.com/spring-cloud/spring-cloud-connectors/issues/244#issuecomment-440714085) is the best way to work around the issue you're having. 

As an example, the Spring Cloud Services client libraries do depend on Spring Security, and [recommend a similar approach](https://docs.pivotal.io/spring-cloud-services/2-0/common/service-registry/writing-client-applications.html#disable-http-basic-auth) for applications that don't want the default Security applied to the application that uses the SCS client libs. 

As Spring Cloud Connectors is not being used, I'm going to close this issue as not related to this project.
