### ISSUE TITLE
pom not deployed properly for 2.0.4.RELEASE

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-connectors#245]
Building a project against `spring-cloud-connectors-core:2.0.4.RELEASE` I get

```
[WARNING] The POM for org.springframework.cloud:spring-cloud-connectors-core:jar:2.0.4.RELEASE is missing, no dependency information available
```

I don't see a reference to `2.0.4.RELEASE` [on Maven central](https://search.maven.org/search?q=g:org.springframework.cloud%20AND%20a:spring-cloud-connectors-core&core=gav)

The pom is also missing from the [Sonatype's OSS release repository](https://oss.sonatype.org/content/repositories/releases/org/springframework/cloud/spring-cloud-connectors-core/2.0.4.RELEASE/)

**Comment by scottfrederick** [comment]
Thanks @snicoll, I'm looking at this now.

**Comment by scottfrederick** [comment]
The `.pom` file is now in the [Sonatype OSS repository](https://oss.sonatype.org/content/repositories/releases/org/springframework/cloud/spring-cloud-connectors-core/2.0.4.RELEASE/) and the [Maven Central repository](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-connectors-core/2.0.4.RELEASE/). 

The Maven Central [search index](https://search.maven.org/search?q=g:org.springframework.cloud%20AND%20a:spring-cloud-connectors-core&core=gav) should get updated soon.
