### ISSUE TITLE
support for Azure Kubernetes Service and azure broker 

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-connectors#250]
Please add support for such automatic lookup in spring cloud apps with OSB bindings for Azure managed services (https://github.com/Azure/open-service-broker-azure/blob/master/docs/quickstart-aks.md#configure-the-cluster-with-open-service-broker-for-azure , https://github.com/Azure/open-service-broker-azure#getting-started-on-kubernetes ) e.g. using Kubernetes ns/ environment / tags for a broad developer experience.
With managed bindings make us of rotating credentials to improve security.

Maybe i oversaw something, cause there are many github projects from pivotal and microsoft in this area and till now there are two platforms (cloudfoundry,kubernetes) supported but not kubernetes 

Related:
https://github.com/Microsoft/azure-spring-boot/issues/262 
https://github.com/Microsoft/spring-cloud-azure/issues/397
https://github.com/spring-cloud/spring-cloud-connectors/issues/248

**Comment by scottfrederick** [comment]
@cforce Spring Cloud Connectors currently supports only Heroku and Cloud Foundry. There is no support for any services on Kubernetes at this time, and there are no immediate plans to add this support. 

Even on Cloud Foundry, Spring Cloud Connectors does not include support for all services provided by the Azure service broker. Microsoft is supporting the [Azure Spring Boot](https://github.com/Microsoft/azure-spring-boot) library that you mentioned as an alternative to using Connectors for those services. I don't know if they plan to add support for Kubernetes in that project.
