### ISSUE TITLE
DataSource properties no longer set

### ISSUE THREAD

**Issue by dietzsch** [spring-cloud/spring-cloud-connectors#253]
In the past we had code that has set properties on the DataSource injected by the Cloud Connector. We had code like this:

    @Bean
    @ConfigurationProperties(prefix = "spring.datasource.tomcat")
    public DataSource dataSource() {
        DataSource ds = cloud().getSingletonServiceConnector(DataSource.class, null);
        return ds;
    }

In parallel we had the following properties set in the application.yml:

    spring:
      datasource:
        tomcat:
          max-active: 50
          max-idle: 40
          min-idle: 4
          test-on-borrow: true
          test-while-idle: true
          validation-query: select 1

So far this code worked fine till the move to the latest Spring Boot 1.5.19 where the fix for issue #237 is included. This commit contains a new DataSource class (org.springframework.jdbc.datasource.DelegatingDataSource) that prevents that the @ConfigurationProperties annotation can set the config properties on the returned bean, as this new class does not offer the necessary methods to set these properties.

**Comment by dietzsch** [comment]
I have implemented the following workaround to enable that the custom properties are set on the DataSource:

    @Bean
    @ConfigurationProperties(prefix = "spring.datasource.tomcat")
    public DataSource dataSource() {
        DataSource ds = cloud().getSingletonServiceConnector(DataSource.class, null);
        if (ds instanceof DelegatingDataSource) {
            ds = ((DelegatingDataSource) ds).getTargetDataSource();
        }
        return ds;
    }

This works and resolved the issue, but is only a workaround.

**Comment by chinnitv** [comment]
Is this expected to be fixed soon? We also are having the same issue and currently the workaround from @dietzsch works like a charm. But I would like a more permanent fix and I dont want to make any assumptions about the type of `DataSource` returned by the Spring Service Connector.

**Comment by alexconanlai** [comment]
I have an issue a little same.
We use following code to get data source in cloud foundry:
`public class CloudDatabaseConfig extends AbstractCloudConfig {
           public DataSource dataSource() throws SQLException {
  final DataSourceConfig dbConfig = new DataSourceConfig(null, connConfig, dataSourceNames);
DataSource dataSource =  connectionFactory().dataSource(dbConfig));
     }
}`
we find that the dataSource is `UrlDecodingDataSource`.
this happened in "spring-cloud-spring-service-connector 2.0.4.RELEASE", when we use "2.0.3.RELEASE", the dataSource is `HikariDataSource`.

Question is how to let us get the `HikariDataSource` when use "spring-cloud-spring-service-connector 2.0.4.RELEASE" except for using `((DelegatingDataSource) ds).getTargetDataSource()`?

**Comment by scottfrederick** [comment]
I'm looking into how this can be fixed without losing the ability that was added in PR #239. 

> I dont want to make any assumptions about the type of DataSource returned by the Spring Service Connector.

If you are counting on the type returned from Connectors being anything other than `javax.sql.DataSource`, then you are already making assumptions that come with some risk.

Connectors will create a `DataSource` bean as one of the following types: 

* `org.apache.tomcat.jdbc.pool.DataSource`
* `org.apache.tomcat.dbcp.dbcp.BasicDataSource`
* `org.apache.tomcat.dbcp.dbcp2.BasicDataSource`
* `org.apache.commons.dbcp2.BasicDataSource`
* `org.apache.commons.dbcp.BasicDataSource`
* `com.zaxxer.hikari.HikariDataSource`
* `org.springframework.jdbc.datasource.SimpleDriverDataSource`

The concrete type that gets created depends on the connection pooling libraries Connectors finds on the application classpath. Casting the `DataSource` return value to one of these concrete types without first verifying the type could lead to runtime exceptions if another connection pooling library with higher priority finds its way onto the classpath. 

These concrete types have similar properties, but use different names for those properties. Connectors attempts to rationalize these differences in properties from a common [`PoolConfig` mechanism](https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/service/PooledServiceConnectorConfig.java#L23-L97). Attempting to set properties on the return value with fixed names like `max-active`, `max-idle`, and `min-idle` without verifying that the type being returned is one that has properties with those names could lead to surprises if the returned type changes.

**Comment by scottfrederick** [comment]
The Spring Cloud Connectors project is [in maintenance mode](https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services), in favor of the newer [Java CFEnv](https://github.com/pivotal-cf/java-cfenv) project. If this feature is still desired, please [file an issue](https://github.com/pivotal-cf/java-cfenv/issues/new) in the Java CfEnv project.
