### ISSUE TITLE
Remove validation query for PostgreSQL data source creator

### ISSUE THREAD

**Issue by metacubed** [spring-cloud/spring-cloud-connectors#256]
The PostgreSQL driver implements the JDBC4 `isValid()` method since [version 9.1](https://github.com/pgjdbc/pgjdbc/blob/REL9_1_STABLE/org/postgresql/jdbc4/AbstractJdbc4Connection.java#L116).

Older versions just used `SELECT 1`, but newer versions make an efficient check without executing a query. For example, see [version 42.2.5](https://github.com/pgjdbc/pgjdbc/blob/REL42.2.5/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L1363).

We should remove the default validation query specified in [PostgresqlDataSourceCreator](https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/service/relational/PostgresqlDataSourceCreator.java#L14) and let the PostgreSQL driver implementation handle validation.

**Comment by scottfrederick** [comment]
The Spring Cloud Connectors project is [in maintenance mode](https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services), in favor of the newer [Java CFEnv](https://github.com/pivotal-cf/java-cfenv) project. If this feature is still desired, please [file an issue](https://github.com/pivotal-cf/java-cfenv/issues/new) in the Java CfEnv project.
