### ISSUE TITLE
Support for reactive mongodb connection

### ISSUE THREAD

**Issue by andyalbert** [spring-cloud/spring-cloud-connectors#294]
I'm trying to deploy my project on cloud foundry, after adding the connector and cloud foundry dependencies, I found that the `AbstractCloudConfig` only supports blocking MongoDB, so when I try to deploy, it keeps telling me that it needs `reactivemongotemplate`

I wish you can add the support for this.
Thanks

**Comment by scottfrederick** [comment]
@andyalbert Please take a look at the [Java CFEnv](https://github.com/pivotal-cf/java-cfenv#using-spring-boot) project. This new project is intended to be used by Spring Boot applications on CF, and works by mapping service bindings to Boot auto-configuration properties. Boot supports [reactive MongoDB auto-configuration](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-mongodb), so this should give you  what you're looking for.

**Comment by andyalbert** [comment]
@scottfrederick Thanks for your answer, I was able to deploy the project using auto-configuration (adding the database URI in the `application.yml` file)

**Comment by scottfrederick** [comment]
> I was able to deploy the project using auto-configuration 

Great!

> adding the database URI in the application.yml file

Do you mean you manually put the URI in `application.yml`? Does it also work if you add `io.pivotal.cfenv:java-cfenv-boot` to the application and let Java CFEnv [set the URI](https://github.com/pivotal-cf/java-cfenv/blob/master/java-cfenv-boot/src/main/java/io/pivotal/cfenv/spring/boot/MongoCfEnvProcessor.java#L41-L44) from `VCAP_SERVICES`?

**Comment by andyalbert** [comment]
Actually what I did was to manually add the URI in `application.yml` file, I didn't try the second solution as I found the first to be fast forward as I was in a hurry.
