### ISSUE TITLE
Maintenence mode?

### ISSUE THREAD

**Issue by michael-wirth** [spring-cloud/spring-cloud-connectors#303]
Is the whole connectors project in maintenence mode or only the cloudfoundry connector? what about the other cloud platforms eg. Kubernetes?

**Comment by scottfrederick** [comment]
The entire project is in maintenance mode. The cloudfoundry connector was by far the most widely used cloud connector. The heroku connector was lightly used (based on the volume of issues and enhancement requests). The localconfig connector was only used for local testing, and the combination of Boot properties and Spring profiles is much easier to use than localconfig. 

The Connectors project never had support for kubernetes.
