### ISSUE TITLE
New release for jacksonVersion = "2.10.0" ?

### ISSUE THREAD

**Issue by scti1016** [spring-cloud/spring-cloud-connectors#307]
Hi,

do you already have a release planned for the changed jacksonVersion = "2.10.0"
from commit https://github.com/spring-cloud/spring-cloud-connectors/commit/a3c61d44567731dd9ae5df91074fad9475221a5c ?

Best regards
scti1016

**Comment by corang** [comment]
Bump, this would be super useful if one of the contributors could push one out @royclarkson

**Comment by mdupuis13** [comment]
Bump, this would be super useful... as spring-cloud-cloudfoundry-connector-2.0.6.RELEASE.pom seems to force 2.9.9.1 on us making my projects fail the OWASP dependencyCheck.

**Comment by scottfrederick** [comment]
I'm planning to publish a release during the week of Nov 25.

**Comment by scti1016** [comment]
> 
> 
> I'm planning to publish a release during the week of Nov 25.

Any updates for this?
