### ISSUE TITLE
spring-cloud-connector fails to detect MongoDB service broker (DNS Seedlist Connection Format) in PCF

### ISSUE THREAD

**Issue by MikeQin** [spring-cloud/spring-cloud-connectors#311]
Since MongoDB 3.6, MongoDB supports "**DNS Seedlist Connection Format**", which means the connection string looks like this: `mongodb+srv://server.example.com/`.

However, when deploying my Spring Boot app to PCF, my app failed to bind the MongoDB service broker due to the fact that my app couldn't find any proper MongoDB service broker to bind. The exception was:

> org.springframework.cloud.CloudException: No suitable ServiceConnectorCreator found

After working with infrastructure engineers, we've figured out that adding a tag `mongodb` to MongoDB service broker helps solve the issue. 

**It means without the `mongodb` tag, `spring-cloud-cloudfoundry-connector` and `spring-cloud-spring-service-connector` failed to auto scan `mongodb+srv` protocol format for detecting MongoDB service broker, and eventually failed to bind the app to the MongoDB service broker during deployment**.

The current remedy to the issue is to add a `mongodb` tag to MongoDB service broker configuration.

The Spring Boot app `build.gradle` is attached for your reference.

```
plugins {
	id 'org.springframework.boot' version '2.1.6.RELEASE'
	id 'java'
}

apply plugin: 'io.spring.dependency-management'

group = 'com.exaple'
version = '1.0'
sourceCompatibility = '11'
targetCompatibility = '11'

configurations {
	developmentOnly
	runtimeClasspath {
		extendsFrom developmentOnly
	}
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.cloud:spring-cloud-spring-service-connector'
	implementation 'org.springframework.cloud:spring-cloud-cloudfoundry-connector'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

**Comment by scottfrederick** [comment]
> The current remedy to the issue is to add a mongodb tag to MongoDB service broker configuration.

Is this remedy not sufficient? 

Note that this project is [in maintenance mode](https://github.com/spring-cloud/spring-cloud-connectors#spring-cloud-connectors-), and we are unlikely to make any changes that aren't security-related. You should migrate to the [Java CFEnv](https://github.com/pivotal-cf/java-cfenv) project instead. If Java CFEnv needs additional detection logic for this MongoDB case, you can[ file an issue](https://github.com/pivotal-cf/java-cfenv/issues/new) there.
