### ISSUE TITLE
MailSenderCreator Create Method accepts the ServiceConnectorConfig object, but does not set the config property to JavaMailSender

### ISSUE THREAD

**Issue by chetanti** [spring-cloud/spring-cloud-connectors#312]
The below create method accepts config, but it does not set property to JavaMailSender.

 public JavaMailSender create(SmtpServiceInfo serviceInfo, ServiceConnectorConfig config) {
        JavaMailSenderImpl mailSender = new JavaMailSenderImpl();
        mailSender.setHost(serviceInfo.getHost());
        mailSender.setPort(serviceInfo.getPort());
        mailSender.setUsername(serviceInfo.getUserName());
        mailSender.setPassword(serviceInfo.getPassword());
        return mailSender;
    }

Can you please tell , how to set properties . 
i.e 
Properties properties = new Properties();
        properties.setProperty("mail.smtp.starttls.enable", "true");
        properties.setProperty("mail.properties.mail.debug", "true");
        properties.setProperty("mail.smtp.writetimeout", "5000");
        properties.setProperty("mail.smtp.timeout", "3000");
        properties.setProperty("mail.smtp.connectiontimeout", "5000");
        mailSender.setJavaMailProperties(properties);

Let me know in case more information is required.

**Comment by scottfrederick** [comment]
Spring Cloud Connectors is [in maintenance mode](https://github.com/spring-cloud/spring-cloud-connectors#spring-cloud-connectors). Please consider migrating to [Java CFEnv](https://github.com/pivotal-cf/java-cfenv) and creating an issue in that project if you can't configure it as desired.
