### ISSUE TITLE
spring-cloud-cloudfoundry-connector 2.0.7.RELEASE can't be used in a modular Java 11 project

### ISSUE THREAD

**Issue by nictas** [spring-cloud/spring-cloud-connectors#313]
I'm trying to use `spring-cloud-cloudfoundry-connector` in my modular Java 11 [project](https://github.com/cloudfoundry-incubator/multiapps-controller). This is what I have in my `module-info.java` file:
```
open module org.cloudfoundry.multiapps.controller.web {

    ...

    requires spring.cloud.cloudfoundry.connector; // This is an "automatic module name" that's derived from the name of the artifact "spring-cloud-cloudfoundry-connector-2.0.7.RELEASE.jar" (dashes are replaced with dots).
    requires spring.cloud.spring.service.connector;

    ...

}
```
This should work, but I get the following error while compiling my project:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Workspace/multiapps-controller/multiapps-controller-web/src/main/java/module-info.java:[52,39] module not found: spring.cloud.cloudfoundry.connector
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
After enabling the debug output of maven, I can see the following warning in the build log:
```
[WARNING] Can't extract module name from spring-cloud-cloudfoundry-connector-2.0.7.RELEASE.jar: Provider class com.fasterxml.jackson.core.JsonFactory not in module
```
I assume that this is because `spring-cloud-cloudfoundry-connector` [shadows](https://github.com/spring-cloud/spring-cloud-connectors/blob/4cbee67434fddc0aa488c38215259db38ed5380a/spring-cloud-cloudfoundry-connector/build.gradle#L20) `jackson-databind`.

**Comment by scottfrederick** [comment]
@nictas  As [noted in the README](https://github.com/spring-cloud/spring-cloud-connectors#spring-cloud-connectors-), the Spring Cloud Connectors project is in maintenance mode. The `spring-cloud-cloudfoundry-connector` module does in fact shadow Jackson libraries. This is one of the problems with maintaining the library and one of the reasons we chose to replace it with the [Java CFEnv](https://github.com/pivotal-cf/java-cfenv) project. Removing the Jackson shading would break backward compatibility for many users of the library and would require a major version release, which we won't be doing. 

If your project used Spring Boot the migration from Connectors to Java CFEnv would be pretty seamless, but it looks like your project is mostly using the lower-level Connectors API to get information and credentials from a service. You should be able to move this over to Java CFEnv using its [lower-level API](https://github.com/pivotal-cf/java-cfenv#basic-usage) to retrieve the same information. 

Patterns using Connectors like:

```
CloudFactory cloudFactory = new CloudFactory();
Cloud cloud = cloudFactory.getCloud();
ServiceInfo serviceInfo = cloud.getServiceInfo(serviceName);
String value = serviceInfo.getValue();
```

would be replaced with something like:

```
CfEnv cfEnv = new CfEnv();
CfCredentials credentials = cfEnv.findCredentialsByName(serviceName);
String value = credentials.getString("value");
```

I'd be happy to provide any assistance I can with moving the project from Connectors to Java CFEnv so it is better positioned for Java 11 and beyond.

**Comment by nictas** [comment]
Thanks for the info! I was able to migrate our project to Java CFEnv. :)
