### ISSUE TITLE
Allow creation of DataSource without requiring dependency on spring-cloud-connector

### ISSUE THREAD

**Issue by ramnivas** [spring-cloud/spring-cloud-connectors#5]
Since `DataSource` and its subclasses are in `spring-service-connector`, unless user adds the latter as a dependency, creating `DataSource` connector is not possible. Unlike other connector types (`MongoDbFactory`), `DataSource` doesn't have any inherent dependency on Spring. Thus, it should be possible to move its creation in the `core` iself.

The tricky part is allowing the use of connection pool (which currently uses Spring classes such as `BeanWrapper`).

**Comment by cgfrost** [comment]
+1

I hit this issue recently as well. Working on a Play sample app that doesn't use Spring other then this connector code. It's OK having the extra dependency for now but would be nice to scrap it in the future.
