### ISSUE TITLE
Inconsistent terminology for Heroku App ID

### ISSUE THREAD

**Issue by chrylis** [spring-cloud/spring-cloud-connectors#53]
The current code uses `SPRING_CLOUD_APP_NAME` to identify an application name from within Heroku, but the API refers to the value in question as `appId()`. Keep as a wart or breaking-change to a consistent `SPRING_CLOUD_APP_ID`?

Note that the way I determine whether the local connector should activate is to look for `spring.cloud.appId`; if we extend that to an environment scan, the values would semantically mean the same thing, but the current logic would get a false-positive on the local connector, so that would need to be addressed somehow.

**Comment by scottfrederick** [comment]
Since this library has been released for a while now and is in wider use, let's not implement this breaking change.
