### ISSUE TITLE
Spring Cloud BOM

### ISSUE THREAD

**Issue by chrylis** [spring-cloud/spring-cloud-connectors#56]
I'm glad to see the main Spring projects including BOM POMs now, but I don't know how to create one in Gradle (other than the obvious fragile XML template file). It would be very helpful to have one for Spring Cloud, especially for testing live applications against development versions of SC.

**Comment by scottfrederick** [comment]
Spring Cloud has release trains with BOMs. Spring Boot depends on Connectors, and the Spring Cloud BOM depends on Spring Boot, so Connectors is excluded from the Spring Cloud BOM to prevent a recursive dependency graph.
