### ISSUE TITLE
AbstractCloudConnector#getServiceInfos called multiple times

### ISSUE THREAD

**Issue by chrylis** [spring-cloud/spring-cloud-connectors#65]
On startup, I notice that `getServiceInfos()` gets called multiple times; apparently, it gets called once to identify the service names, and then it gets called again to specifically retrieve each service by name. The implementation in `AbstractCloudConnector` delegates to `getServicesData()`, which in all the connectors rebuilds the entire cloud context. I think that `getServiceInfos()` should cache the result before returning; is there a reason not to do this?

**Comment by scottfrederick** [comment]
Closing this due to its age. Please re-open and comment if you think there is sufficient reason to address this.
