### ISSUE TITLE
Dependencies marked as optional aren't

### ISSUE THREAD

**Issue by chrylis** [spring-cloud/spring-cloud-connectors#67]
The dependencies on `spring-rabbit`, `spring-data-mongodb` and `spring-data-redis` are marked as optional, but `AbstractCloudConfig` has a hard linker dependency on them. It might be possible to do some trickery like Spring Boot does with nested classes and conditions that look for the class, but in the meantime, it is probably easiest to remove the "optional".

**Comment by scottfrederick** [comment]
See resolution in #88.
