### ISSUE TITLE
Provide connector for s3 blobstore service (riak cs)

### ISSUE THREAD

**Issue by ramnivas** [spring-cloud/spring-cloud-connectors#71]
Tags are ["riak-cs","s3"]

**Comment by davidehringer** [comment]
Could https://github.com/cloudfoundry-community/spring-cloud-s3-service-connector be modified or extended to fit the bill?  I'm not sure what the riak cs credentials look like.

**Comment by ArthurHlt** [comment]
I've made one with auto-provisioning (give a jcloud `ContextBuilder`), you can find it here:  https://github.com/Orange-OpenSource/cloudfoundry-s3-service-connector .
If you are interested let me know, I could integrate it to [spring-cloud-cloudfoundry-connector](https://github.com/spring-cloud/spring-cloud-connectors/tree/master/spring-cloud-cloudfoundry-connector)
