### ISSUE TITLE
Reduce number of classes shaded in cloudfoundry-connector

### ISSUE THREAD

**Issue by ramnivas** [spring-cloud/spring-cloud-connectors#73]
Currently, we are shading in the whole jackson library thus increasing the jar file size.

**Comment by SvetlinZarev** [comment]
Do you really need Jackson ? It's just used to map  VCAP_SERVICES/APPLICATION to a java.util.Map, which can easily be done with lets say org.json:json. If you are interested in replacing jackson with org.json you might be interested in https://github.com/SvetlinZarev/spring-cloud-connectors/commit/8767b1e62e58a75dc690ab4d0ed4e685b7d88fe2 

Kind regards,
Svetlin
