### ISSUE TITLE
Provide CloudConnector for OpenShift

### ISSUE THREAD

**Issue by aug70** [spring-cloud/spring-cloud-connectors#90]
It'd be great to have a connector for RedHat OpenShift.

**Comment by metacubed** [comment]
I'd like to help out on this feature. What's a good starting point?

**Comment by scottfrederick** [comment]
@metacubed There is some basic information here: https://github.com/spring-cloud/spring-cloud-connectors/tree/master/spring-cloud-core#adding-cloud-connectors. 

The best starting point is to look at the [Cloud Foundry cloud connector](https://github.com/spring-cloud/spring-cloud-connectors/tree/master/spring-cloud-cloudfoundry-connector) and [Heroku cloud connector](https://github.com/spring-cloud/spring-cloud-connectors/tree/master/spring-cloud-heroku-connector). An OpenShift cloud connector would serve a similar role.

The role of the cloud connectors is to fetch and parse information from the cloud environment and populate `ServiceInfo` object from that information. For Cloud Foundry, this means parsing the `VCAP_SERVICES` environment variable. For Heroku, this means looking for specific env vars for each type of service. There is a small amount of additional information provided for each cloud platform. 

Spring Cloud Connectors is built for extension, and we don't envision that all cloud extensions will live in this GitHub repo. You can build an OpenShift cloud connector in a separate repo and publish it as a separate artifact, and we can link to it in documentation when it is ready to be used.

**Comment by cforce** [comment]
+1

**Comment by scottfrederick** [comment]
> Spring Cloud Connectors is built for extension, and we don't envision that all cloud extensions will live in this GitHub repo. You can build an OpenShift cloud connector in a separate repo and publish it as a separate artifact, and we can link to it in documentation when it is ready to be used.

To reinforce this point, here are a few Spring Cloud Connectors extensions in their own repos, as a model for how OpenShift support could be implemented: 

* https://github.com/SAP/spring-cloud-sap
* https://github.com/IBM-Bluemix/bluemix-cloud-connectors
* https://github.com/pivotal-cf/spring-cloud-services-connector

**Comment by scottfrederick** [comment]
Additional CloudConnectors will be implemented in separate projects, not the core project.
