### ISSUE TITLE
Relational DataSourceCreator doesn't support the Hikari connection pool

### ISSUE THREAD

**Issue by jbcpollak** [spring-cloud/spring-cloud-connectors#91]
Spring-boot supports the Hikari connection pool (see https://github.com/spring-projects/spring-boot/issues/418), but Spring-Cloud-Connectors does not. This causes problems when projects that use Hikari deploy to Coudfoundry or Heroku, resulting in this error message:

    » 19:19:18.354 [localhost-startStop-1] WARN  o.s.c.s.relational.DataSourceCreator 
        - Found neither DBCP nor Tomcat connection pool on the classpath (no pooling is in effect).

I think it if Spring-boot supports Hikari, Spring-Cloud needs to also.

@brettwooldridge - FYI, thought you'd like to know.

**Comment by scottfrederick** [comment]
Fixed via #92.
