### ISSUE TITLE
Allow for multiple database URLs to be configured for one given provider

### ISSUE THREAD

**Issue by balteo** [spring-cloud/spring-cloud-connectors#93]
It would be nice if spring-cloud-connectors for Heroku allowed to configure **multiple databases URLs for one given provider.**

Let's take the RedisCloud (Redislabs) provider/add-on: I was not able to configure two different Redislabs URLs/endpoints using spring cloud connector. See post [on Stackoverflow here](http://stackoverflow.com/questions/26555734/).

This is a common requirement to have two different Redis instances for the reason explained below by Redislabs:

> Redis currently supports the shared (i.e. numbered) databases functionality, although it is expected > to be obsoleted in its near future versions (i.e. v3). Having shared databases means that the same 
> Redis instance manages multiple databases. Each of these databases has its own key space.

>  As Redis is (mostly) single-threaded, shared databases can and do interfere with each other as one > blocking/resource-heavy command against one shared database will effectively freeze all others as > well. Shared databases are great for development and maybe even for staging purposes, but should > not be used in production. The KEYS command, for example, is a good example of a resource-
> intensive command that should be used with caution (i.e. not in production).

> That is exactly the reason why each of our Redis Cloud instances allow using just one database (the > default, 0-numbered database). This ensures that any two databases in our service will never 
> compete on the resources of a single thread. In fact, trying to use any database other than 0 with our > service should produce an error.

> To use these dedicated instance, simply add databases to your subscription by clicking the Add DB > link from the console. Each dedicated database is provisioned with its own endpoint that you can be > used to connect to.

> We do provide URL per DB.

> sample URLs:

> `redis://<resource_name>:<password>@endpoint:port_no`

If it is indeed possible to use two URLs/endpoints for the same provider, then it could perhaps be documented.

**Comment by scottfrederick** [comment]
@balteo  Neither Cloud Foundry or Heroku support the ability to have multiple URLs for a single Redis database, so I'm closing this issue.
